# Generated by Django 4.0.8 on 2022-11-14 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('print_forms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waybilldata',
            name='auto_model',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Марка авто'),
        ),
        migrations.AlterField(
            model_name='waybilldata',
            name='auto_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Гос. номер'),
        ),
        migrations.AlterField(
            model_name='waybilldata',
            name='driver_entity',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Национальность'),
        ),
        migrations.AlterField(
            model_name='waybilldata',
            name='driver_first_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='waybilldata',
            name='driver_last_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='waybilldata',
            name='driver_license',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Номер в.у.'),
        ),
        migrations.AlterField(
            model_name='waybilldata',
            name='driver_second_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Отчество'),
        ),
        migrations.AlterField(
            model_name='waybilldata',
            name='ownership',
            field=models.CharField(blank=True, choices=[('own', 'Собственность'), ('family', 'Совместная собственность супругов'), ('rent', 'Аренда'), ('leasing', 'Лизинг'), ('free', 'Безвозмездное пользование')], max_length=20, null=True, verbose_name='Тип владения'),
        ),
    ]
