# Generated by Django 4.0.8 on 2022-11-15 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('print_forms', '0002_alter_waybilldata_auto_model_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='docoriginal',
            name='weight_brut',
            field=models.FloatField(default=0, verbose_name='Вес брутто, кг'),
        ),
        migrations.AddField(
            model_name='waybilldata',
            name='quantity',
            field=models.IntegerField(default=0, verbose_name='Количество мест'),
        ),
        migrations.AddField(
            model_name='waybilldata',
            name='weight_brut',
            field=models.FloatField(default=0, verbose_name='Вес брутто, кг'),
        ),
        migrations.AlterField(
            model_name='docoriginal',
            name='weight_payed',
            field=models.FloatField(default=0, verbose_name='Оплачиваемый вес, кг'),
        ),
    ]
