# Generated by Django 4.0.8 on 2022-11-16 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('print_forms', '0004_transdocsdata_remove_docoriginal_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transdocsdata',
            name='value',
            field=models.FloatField(default=0, verbose_name='Стоимость'),
        ),
    ]
