# Generated by Django 4.0.8 on 2022-11-28 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('print_forms', '0008_alter_docoriginal_doc_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docoriginal',
            name='doc_type',
            field=models.CharField(choices=[('auto', 'ТН'), ('cmr', 'CMR'), ('plane', 'AWB'), ('rail', 'СМГС'), ('ship', 'Коносамент'), ('combined', 'ТН'), ('courier', 'ТН')], max_length=50, verbose_name='Тип накладной'),
        ),
    ]
