# Generated by Django 4.0.8 on 2022-11-28 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('print_forms', '0009_alter_docoriginal_doc_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transdocsdata',
            name='auto_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Гос. номер'),
        ),
    ]
