# Generated by Django 4.0.8 on 2023-01-17 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('print_forms', '0010_alter_transdocsdata_auto_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='transdocsdata',
            name='race_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='transdocsdata',
            name='doc_date',
            field=models.DateField(verbose_name='Дата отгрузки'),
        ),
    ]
