# Generated by Django 4.1.7 on 2023-02-27 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('print_forms', '0013_alter_transdocsdata_doc_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transdocsdata',
            name='driver_entity',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Гражданство'),
        ),
    ]
