# Generated by Django 4.1.9 on 2023-07-15 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('print_forms', '0015_alter_docoriginal_doc_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='transdocsdata',
            name='driver_passport_issued_at',
            field=models.DateField(blank=True, null=True, verbose_name='Когда выдан'),
        ),
        migrations.AddField(
            model_name='transdocsdata',
            name='driver_passport_issuer',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Кем выдан'),
        ),
        migrations.AddField(
            model_name='transdocsdata',
            name='driver_passport_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Серия и номер паспорта'),
        ),
    ]
