# Generated by Django 4.1.9 on 2023-07-16 21:48

from django.db import migrations, models
import django.db.models.deletion
import print_forms.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0103_order_created_by'),
        ('print_forms', '0016_transdocsdata_driver_passport_issued_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RandomDocScan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('doc_name', models.CharField(max_length=50, verbose_name='Тип документа')),
                ('doc_number', models.CharField(max_length=100, verbose_name='Номер документа')),
                ('doc_date', models.DateField(verbose_name='Дата документа')),
                ('rd_file', models.FileField(upload_to=print_forms.models.path_by_order, verbose_name='Скан документа')),
                ('segment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='randoms', to='orders.transitsegment', verbose_name='Плечо перевозки')),
                ('transit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='randoms', to='orders.transit', verbose_name='Перевозка')),
            ],
        ),
    ]
