# Generated by Django 4.1.9 on 2023-07-17 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('print_forms', '0017_randomdocscan'),
    ]

    operations = [
        migrations.AddField(
            model_name='transdocsdata',
            name='driver_phone',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Тел.'),
        ),
    ]
