# Generated by Django 4.1.10 on 2023-08-15 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('print_forms', '0018_transdocsdata_driver_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='transdocsdata',
            name='doc_num_trans',
            field=models.CharField(default='', max_length=255, verbose_name='Номер основного транспортного документа'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transdocsdata',
            name='doc_type',
            field=models.CharField(default='', max_length=10, verbose_name='Тип основного транспортного документа'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='transdocsdata',
            name='doc_number',
            field=models.CharField(max_length=100, unique=True, verbose_name='Номер ЭР'),
        ),
    ]
