# Generated by Django 4.1.10 on 2023-08-15 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('print_forms', '0019_transdocsdata_doc_num_trans_transdocsdata_doc_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transdocsdata',
            name='doc_type',
            field=models.CharField(choices=[('auto', 'ТН'), ('cmr', 'CMR'), ('plane', 'AWB'), ('rail', 'СМГС'), ('ship', 'Коносамент'), ('combined', 'ТН'), ('courier', 'ТН')], max_length=10, verbose_name='Тип основного транспортного документа'),
        ),
    ]
