# Generated by Django 4.1.10 on 2023-08-16 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('print_forms', '0020_alter_transdocsdata_doc_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='transdocsdata',
            name='auto_tonnage',
            field=models.IntegerField(blank=True, null=True, verbose_name='Тоннаж'),
        ),
    ]
