# Generated by Django 4.1.11 on 2023-09-10 22:36

import datetime
from django.db import migrations, models


def fill_doc_date_trans(apps, schema_editor):
    TransDocsData = apps.get_model('print_forms', 'TransDocsData')
    for i in TransDocsData.objects.all():
        i.doc_date_trans = i.doc_date
        i.save()


class Migration(migrations.Migration):

    dependencies = [
        ('print_forms', '0022_remove_docoriginal_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='transdocsdata',
            name='doc_date_trans',
            field=models.DateField(default=datetime.datetime(2023, 9, 10, 22, 36, 35, 906670), verbose_name='Дата основного транспортного документа'),
            preserve_default=False,
        ),
        migrations.RunPython(fill_doc_date_trans, reverse_code=migrations.RunPython.noop)
    ]
