# Generated by Django 4.1.11 on 2023-09-26 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('print_forms', '0023_transdocsdata_doc_date_trans'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transdocsdata',
            options={'verbose_name': 'отгрузка', 'verbose_name_plural': 'отгрузки'},
        ),
    ]
