# Generated by Django 4.1.13 on 2024-03-19 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('print_forms', '0026_alter_docoriginal_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='docoriginal',
            options={'verbose_name': 'скан', 'verbose_name_plural': 'сканы'},
        ),
    ]
