# Generated by Django 4.1.13 on 2024-03-22 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('print_forms', '0027_alter_docoriginal_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='transdocsdata',
            name='support_docs',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Сопроводительные документы'),
        ),
    ]
