# Generated by Django 4.1.13 on 2024-08-01 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('print_forms', '0028_transdocsdata_support_docs'),
    ]

    operations = [
        migrations.AddField(
            model_name='transdocsdata',
            name='armed_security',
            field=models.BooleanField(default=False, verbose_name='Вооруженная охрана'),
        ),
        migrations.AddField(
            model_name='transdocsdata',
            name='driver_license_issued_at',
            field=models.DateField(blank=True, null=True, verbose_name='Когда выдано в.у.'),
        ),
    ]
