# Generated by Django 4.1.13 on 2024-08-01 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('print_forms', '0029_transdocsdata_armed_security_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transdocsdata',
            name='auto_ownership',
        ),
    ]
