# Generated by Django 4.0.8 on 2022-10-24 17:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0078_alter_extorder_date_alter_extorder_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='WaybillData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('waybill_number', models.CharField(max_length=100, unique=True, verbose_name='Номер транспортной накладной')),
                ('driver_last_name', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('driver_first_name', models.CharField(max_length=50, verbose_name='Имя')),
                ('driver_second_name', models.CharField(max_length=50, verbose_name='Отчество')),
                ('driver_license', models.CharField(max_length=50, verbose_name='Номер в.у.')),
                ('driver_entity', models.CharField(default='РФ', max_length=50, verbose_name='Национальность')),
                ('auto_model', models.CharField(max_length=100, verbose_name='Марка авто')),
                ('auto_number', models.CharField(max_length=20, verbose_name='Гос. номер')),
                ('ownership', models.CharField(choices=[('own', 'Собственность'), ('family', 'Совместная собственность супругов'), ('rent', 'Аренда'), ('leasing', 'Лизинг'), ('free', 'Безвозмездное пользование')], default='own', max_length=20, verbose_name='Тип владения')),
                ('segment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waybills', to='orders.transitsegment', verbose_name='Плечо перевозки')),
            ],
        ),
    ]
