# Generated by Django 4.0.8 on 2022-11-16 10:35

from django.db import migrations, models
import django.db.models.deletion
import print_forms.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0082_alter_order_client_number'),
        ('print_forms', '0003_docoriginal_weight_brut_waybilldata_quantity_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransDocsData',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('doc_number', models.CharField(max_length=100, unique=True, verbose_name='Номер ТН')),
                ('doc_date', models.DateField(verbose_name='Дата накладной')),
                ('file_name', models.CharField(max_length=100, verbose_name='Имя файла')),
                ('quantity', models.IntegerField(default=0, verbose_name='Количество мест')),
                ('weight_brut', models.FloatField(default=0, verbose_name='Вес брутто, кг')),
                ('driver_last_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Фамилия')),
                ('driver_first_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Имя')),
                ('driver_second_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Отчество')),
                ('driver_license', models.CharField(blank=True, max_length=50, null=True, verbose_name='Номер в.у.')),
                ('driver_entity', models.CharField(blank=True, max_length=50, null=True, verbose_name='Национальность')),
                ('auto_model', models.CharField(blank=True, max_length=100, null=True, verbose_name='Марка авто')),
                ('auto_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='Гос. номер')),
                ('auto_ownership', models.CharField(blank=True, choices=[('own', 'Собственность'), ('family', 'Совместная собственность супругов'), ('rent', 'Аренда'), ('leasing', 'Лизинг'), ('free', 'Безвозмездное пользование')], max_length=20, null=True, verbose_name='Тип владения')),
            ],
        ),
        migrations.RemoveField(
            model_name='docoriginal',
            name='file',
        ),
        migrations.AddField(
            model_name='docoriginal',
            name='sr_file',
            field=models.FileField(default='', upload_to=print_forms.models.path_by_order, verbose_name='Скан ЭР'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='docoriginal',
            name='td_file',
            field=models.FileField(default='', upload_to=print_forms.models.path_by_order, verbose_name='Скан накладной'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='docoriginal',
            name='doc_type',
            field=models.CharField(choices=[('auto', 'ТН'), ('plane', 'AWB'), ('rail', 'СМГС'), ('ship', 'Коносамент')], max_length=50, verbose_name='Тип накладной'),
        ),
        migrations.DeleteModel(
            name='WaybillData',
        ),
        migrations.AddField(
            model_name='transdocsdata',
            name='doc_original',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='waybill', to='print_forms.docoriginal', verbose_name='Оригинал документа'),
        ),
        migrations.AddField(
            model_name='transdocsdata',
            name='ext_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='waybills', to='orders.extorder', verbose_name='Исх. поручение'),
        ),
        migrations.AddField(
            model_name='transdocsdata',
            name='segment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waybills', to='orders.transitsegment', verbose_name='Плечо перевозки'),
        ),
    ]
