# Generated by Django 4.0.8 on 2022-11-24 15:48

from django.db import migrations, models
import django.db.models.deletion
import print_forms.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0088_transit_from_date_wanted_transit_to_date_wanted'),
        ('print_forms', '0006_docoriginal_value'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='docoriginal',
            name='sr_file',
        ),
        migrations.AlterField(
            model_name='docoriginal',
            name='value',
            field=models.FloatField(default=0, verbose_name='Стоимость груза'),
        ),
        migrations.CreateModel(
            name='ShippingReceiptOriginal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('doc_number', models.CharField(max_length=100, unique=True, verbose_name='Номер')),
                ('doc_date', models.DateField(verbose_name='Дата документа')),
                ('load_date', models.DateField(verbose_name='Дата погрузки')),
                ('sr_file', models.FileField(upload_to=print_forms.models.path_by_order, verbose_name='Скан ЭР')),
                ('segment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to='orders.transitsegment', verbose_name='Плечо перевозки')),
                ('transit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to='orders.transit', verbose_name='Перевозка')),
            ],
        ),
    ]
