# Generated by Django 4.0.8 on 2022-10-25 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('print_forms', '0006_waybilldata_waybill_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docoriginal',
            name='doc_type',
            field=models.CharField(choices=[('auto', 'ТН'), ('plane', 'AWB'), ('rail', 'СМГС'), ('ship', 'Коносамент')], max_length=50, verbose_name='Тип документа'),
        ),
    ]
