# Generated by Django 4.0.8 on 2022-11-25 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('print_forms', '0007_remove_docoriginal_sr_file_alter_docoriginal_value_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docoriginal',
            name='doc_type',
            field=models.CharField(choices=[('auto', 'ТН'), ('cmr', 'CMR'), ('plane', 'AWB'), ('rail', 'СМГС'), ('ship', 'Коносамент')], max_length=50, verbose_name='Тип накладной'),
        ),
        migrations.AlterField(
            model_name='transdocsdata',
            name='doc_date',
            field=models.DateField(verbose_name='Дата документа'),
        ),
        migrations.AlterField(
            model_name='transdocsdata',
            name='doc_number',
            field=models.CharField(max_length=100, unique=True, verbose_name='Номер документа'),
        ),
    ]
