# Generated by Django 4.0.8 on 2023-01-19 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('print_forms', '0012_alter_transdocsdata_race_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transdocsdata',
            name='doc_number',
            field=models.CharField(max_length=100, unique=True, verbose_name='Номер транспортного документа'),
        ),
    ]
