# Generated by Django 4.0.2 on 2022-05-16 07:39

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_orderhistory_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderhistory',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 16, 7, 39, 40, 597442, tzinfo=utc), verbose_name='Время'),
        ),
        migrations.AlterField(
            model_name='transithistory',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 16, 7, 39, 40, 597442, tzinfo=utc), verbose_name='Время'),
        ),
    ]
