# Generated by Django 4.0.2 on 2022-05-16 07:40

import datetime
from django.db import migrations, models
import django.utils.timezone
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_orderhistory_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderhistory',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 16, 7, 40, 40, 672354, tzinfo=utc), verbose_name='Время'),
        ),
        migrations.AlterField(
            model_name='transithistory',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Время'),
        ),
    ]
