# Generated by Django 4.0.2 on 2022-03-30 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_order_price_alter_order_price_carrier_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('new', 'Ожидает обработки'), ('bargain', 'Согласование ставок'), ('pending', 'Обрабатывается перевозчиком'), ('in_progress', 'В пути'), ('completed', 'Выполнено'), ('rejected', 'Отменено')], default='new', max_length=50),
        ),
        migrations.AlterField(
            model_name='orderhistory',
            name='status',
            field=models.CharField(choices=[('new', 'Ожидает обработки'), ('bargain', 'Согласование ставок'), ('pending', 'Обрабатывается перевозчиком'), ('in_progress', 'В пути'), ('completed', 'Выполнено'), ('rejected', 'Отменено')], default='new', max_length=50, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='transit',
            name='quantity',
            field=models.FloatField(default=0, verbose_name='Количество мест'),
        ),
        migrations.AlterField(
            model_name='transit',
            name='quantity_payed',
            field=models.FloatField(default=0, verbose_name='Количество мест'),
        ),
        migrations.AlterField(
            model_name='transit',
            name='volume',
            field=models.FloatField(default=0, verbose_name='Объем'),
        ),
        migrations.AlterField(
            model_name='transit',
            name='volume_payed',
            field=models.FloatField(default=0, verbose_name='Объем'),
        ),
        migrations.AlterField(
            model_name='transit',
            name='weight',
            field=models.FloatField(default=0, verbose_name='Вес брутто'),
        ),
        migrations.AlterField(
            model_name='transit',
            name='weight_payed',
            field=models.FloatField(default=0, verbose_name='Вес брутто'),
        ),
        migrations.DeleteModel(
            name='OrderStatus',
        ),
    ]
