# Generated by Django 4.0.2 on 2022-03-30 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_order_status_alter_orderhistory_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('new', 'Ожидает обработки'), ('bargain', 'Согласование ставок'), ('pending', 'Обрабатывается перевозчиком'), ('in_progress', 'В пути'), ('completed', 'Выполнено'), ('rejected', 'Отменено')], db_index=True, default='new', max_length=50, verbose_name='Статус поручения'),
        ),
        migrations.AlterField(
            model_name='transit',
            name='status',
            field=models.CharField(choices=[('new', 'Ожидает обработки'), ('bargain', 'Согласование ставок'), ('pending', 'Обрабатывается перевозчиком'), ('in_progress', 'В пути'), ('completed', 'Выполнено'), ('rejected', 'Отменено')], db_index=True, default='new', max_length=50, verbose_name='Статус поручения'),
        ),
        migrations.AlterField(
            model_name='transithistory',
            name='status',
            field=models.CharField(choices=[('new', 'Ожидает обработки'), ('bargain', 'Согласование ставок'), ('pending', 'Обрабатывается перевозчиком'), ('in_progress', 'В пути'), ('completed', 'Выполнено'), ('rejected', 'Отменено')], default='new', max_length=50, verbose_name='Статус'),
        ),
    ]
