# Generated by Django 4.0.2 on 2022-05-16 07:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_orderhistory_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderhistory',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Время'),
        ),
    ]
