# Generated by Django 4.0.2 on 2022-05-16 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_alter_orderhistory_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='price',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Ставка'),
        ),
        migrations.AlterField(
            model_name='order',
            name='price_carrier',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Закупочная цена поручения'),
        ),
    ]
