# Generated by Django 4.0.2 on 2022-04-05 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_alter_order_status_alter_transit_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtraService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machine_name', models.CharField(max_length=100)),
                ('human_name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'доп. услуга',
                'verbose_name_plural': 'доп. услуги',
            },
        ),
        migrations.RemoveField(
            model_name='cargo',
            name='volume',
        ),
        migrations.AddField(
            model_name='cargo',
            name='currency',
            field=models.CharField(choices=[('RUB', 'Рубль'), ('USD', 'Доллар США'), ('EUR', 'Евро')], default='RUB', max_length=3, verbose_name='Валюта'),
        ),
        migrations.AddField(
            model_name='cargo',
            name='height',
            field=models.FloatField(default=0, verbose_name='Высота'),
        ),
        migrations.AddField(
            model_name='cargo',
            name='length',
            field=models.FloatField(default=0, verbose_name='Длина'),
        ),
        migrations.AddField(
            model_name='cargo',
            name='package_type',
            field=models.CharField(choices=[('cardboard_box', 'Картонная коробка'), ('wooden_box', 'Деревянный ящик'), ('safe_package', 'Сейф-пакет'), ('package', 'Пакет')], default='cardboard_box', max_length=255, verbose_name='Тип упаковки'),
        ),
        migrations.AddField(
            model_name='cargo',
            name='width',
            field=models.FloatField(default=0, verbose_name='Ширина'),
        ),
        migrations.AlterField(
            model_name='cargo',
            name='quantity',
            field=models.IntegerField(default=1, verbose_name='Количество мест'),
        ),
        migrations.AlterField(
            model_name='cargo',
            name='value',
            field=models.FloatField(blank=True, null=True, verbose_name='Заявленная стоимость'),
        ),
        migrations.AlterField(
            model_name='cargo',
            name='weight',
            field=models.FloatField(blank=True, null=True, verbose_name='Вес брутто'),
        ),
        migrations.AlterField(
            model_name='transit',
            name='status',
            field=models.CharField(choices=[('new', 'Ожидает обработки'), ('bargain', 'Согласование ставок'), ('pending', 'Обрабатывается перевозчиком'), ('in_progress', 'В пути'), ('completed', 'Выполнено'), ('rejected', 'Отменено')], db_index=True, default='new', max_length=50, verbose_name='Статус перевозки'),
        ),
    ]
