# Generated by Django 4.0.2 on 2022-04-05 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_extraservice_remove_cargo_volume_cargo_currency_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cargo',
            name='currency',
            field=models.CharField(blank=True, choices=[('RUB', 'Рубль'), ('USD', 'Доллар США'), ('EUR', 'Евро')], default='RUB', max_length=3, null=True, verbose_name='Валюта'),
        ),
    ]
