# Generated by Django 4.0.2 on 2022-05-16 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_alter_order_price_alter_order_price_carrier'),
    ]

    operations = [
        migrations.AddField(
            model_name='transit',
            name='currency',
            field=models.CharField(choices=[('RUB', 'Рубль'), ('USD', 'Доллар США'), ('EUR', 'Евро')], default='RUB', max_length=3, verbose_name='Валюта'),
        ),
    ]
