# Generated by Django 4.0.2 on 2022-05-16 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_transit_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='quantity',
            field=models.FloatField(default=0, verbose_name='Количество мест'),
        ),
        migrations.AddField(
            model_name='order',
            name='weight',
            field=models.FloatField(default=0, verbose_name='Вес брутто'),
        ),
    ]
