# Generated by Django 4.0.2 on 2022-04-05 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_alter_cargo_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='cargo',
            name='extra_services',
            field=models.ManyToManyField(blank=True, null=True, to='orders.ExtraService', verbose_name='Доп. услуги'),
        ),
    ]
