# Generated by Django 4.0.2 on 2022-05-16 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_alter_order_quantity_alter_transit_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='contract',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Договор'),
        ),
    ]
