# Generated by Django 4.0.2 on 2022-04-05 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_alter_cargo_extra_services_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cargo',
            name='value',
            field=models.FloatField(default=0, verbose_name='Заявленная стоимость'),
        ),
    ]
