# Generated by Django 4.0.2 on 2022-04-05 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_alter_cargo_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cargo',
            name='extra_services',
            field=models.ManyToManyField(blank=True, to='orders.ExtraService', verbose_name='Доп. параметры'),
        ),
        migrations.AlterField(
            model_name='cargo',
            name='quantity',
            field=models.IntegerField(default=1, verbose_name='Мест'),
        ),
        migrations.AlterField(
            model_name='cargo',
            name='weight',
            field=models.FloatField(blank=True, null=True, verbose_name='Вес'),
        ),
    ]
