# Generated by Django 4.0.2 on 2022-04-05 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_alter_cargo_extra_services_alter_cargo_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cargo',
            name='currency',
            field=models.CharField(choices=[('RUB', 'Рубль'), ('USD', 'Доллар США'), ('EUR', 'Евро')], default='RUB', max_length=3, verbose_name='Валюта'),
        ),
    ]
