# Generated by Django 4.0.2 on 2022-04-13 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_alter_cargo_currency'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ExtraService',
            new_name='ExtraCargoParams',
        ),
        migrations.AlterModelOptions(
            name='extracargoparams',
            options={'verbose_name': 'доп. параметр груза', 'verbose_name_plural': 'доп. параметры груза'},
        ),
        migrations.RemoveField(
            model_name='cargo',
            name='extra_services',
        ),
        migrations.AddField(
            model_name='cargo',
            name='extra_params',
            field=models.ManyToManyField(blank=True, to='orders.ExtraCargoParams', verbose_name='Доп. параметры'),
        ),
    ]
