# Generated by Django 4.0.2 on 2022-04-13 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_rename_extraservice_extracargoparams_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtraService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machine_name', models.CharField(max_length=100, unique=True)),
                ('human_name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name': 'доп. услуга',
                'verbose_name_plural': 'доп. услуги',
            },
        ),
        migrations.AddField(
            model_name='transit',
            name='extra_services',
            field=models.ManyToManyField(blank=True, to='orders.ExtraService', verbose_name='Доп. услуги'),
        ),
    ]
