# Generated by Django 4.0.2 on 2022-05-26 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0015_alter_transit_price_alter_transit_price_carrier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transit',
            name='status',
            field=models.CharField(choices=[('carrier_select', 'Выбор перевозчика'), ('pickup', 'Забор груза'), ('in_progress', 'В пути'), ('temporary_storage', 'Груз на СВХ (ТО)'), ('transit_storage', 'Груз на транзитном складе'), ('completed', 'Доставлено'), ('rejected', 'Аннулировано')], db_index=True, default='carrier_select', max_length=50, verbose_name='Статус перевозки'),
        ),
        migrations.AlterField(
            model_name='transit',
            name='type',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='Вид перевозки'),
        ),
    ]
