# Generated by Django 4.0.2 on 2022-04-13 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0015_extraservice_transit_extra_services'),
    ]

    operations = [
        migrations.AddField(
            model_name='transit',
            name='from_contact_email',
            field=models.CharField(default='', max_length=255, verbose_name='email'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transit',
            name='from_contact_name',
            field=models.CharField(default='', max_length=255, verbose_name='Контактное лицо'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transit',
            name='from_contact_phone',
            field=models.CharField(default='', max_length=255, verbose_name='Телефон'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transit',
            name='from_inn',
            field=models.CharField(default='', max_length=255, verbose_name='ИНН отправителя'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transit',
            name='from_org',
            field=models.CharField(default='', max_length=255, verbose_name='Юр. наименование отправителя'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transit',
            name='to_contact_email',
            field=models.CharField(default='', max_length=255, verbose_name='email'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transit',
            name='to_contact_name',
            field=models.CharField(default='', max_length=255, verbose_name='Контактное лицо'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transit',
            name='to_contact_phone',
            field=models.CharField(default='', max_length=255, verbose_name='Телефон'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transit',
            name='to_inn',
            field=models.CharField(default='', max_length=255, verbose_name='ИНН получателя'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transit',
            name='to_org',
            field=models.CharField(default='', max_length=255, verbose_name='Юр. наименование получателя'),
            preserve_default=False,
        ),
    ]
