# Generated by Django 4.0.2 on 2022-04-13 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0016_transit_from_contact_email_transit_from_contact_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transit',
            name='quantity_payed',
        ),
        migrations.RemoveField(
            model_name='transit',
            name='volume_payed',
        ),
        migrations.AddField(
            model_name='transit',
            name='wight_volume',
            field=models.FloatField(default=0, verbose_name='Объемный вес'),
        ),
        migrations.AlterField(
            model_name='transit',
            name='weight_payed',
            field=models.FloatField(default=0, verbose_name='Оплачиваемый вес'),
        ),
    ]
