# Generated by Django 4.0.2 on 2022-04-13 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0017_remove_transit_quantity_payed_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transit',
            old_name='wight_volume',
            new_name='weight_volume',
        ),
    ]
