# Generated by Django 4.0.2 on 2022-05-27 12:14

from django.db import migrations, models
import django.db.models.deletion
import orders.models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0019_transit_insurance'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Пояснение')),
                ('file', models.FileField(upload_to=orders.models.path_by_order, verbose_name='Файл')),
                ('public', models.BooleanField(default=False, verbose_name='Видно клиенту')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='docs', to='orders.order', verbose_name='Поручение')),
            ],
        ),
    ]
