# Generated by Django 4.0.2 on 2022-04-14 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0019_transit_sub_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='from_addr_forlist',
            field=models.CharField(default='', max_length=255, verbose_name='Адрес отправления'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='to_addr_forlist',
            field=models.CharField(default='', max_length=255, verbose_name='Адрес доставки'),
            preserve_default=False,
        ),
    ]
