# Generated by Django 4.0.2 on 2022-04-14 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0020_order_from_addr_forlist_order_to_addr_forlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='from_addr_forlist',
            field=models.CharField(editable=False, max_length=255, verbose_name='Адрес отправления'),
        ),
        migrations.AlterField(
            model_name='order',
            name='to_addr_forlist',
            field=models.CharField(editable=False, max_length=255, verbose_name='Адрес доставки'),
        ),
    ]
