# Generated by Django 4.0.2 on 2022-04-15 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0021_alter_order_from_addr_forlist_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='price',
            field=models.FloatField(default=0, verbose_name='Ставка'),
        ),
        migrations.AlterField(
            model_name='order',
            name='price_carrier',
            field=models.FloatField(default=0, verbose_name='Закупочная цена поручения'),
        ),
    ]
