# Generated by Django 4.0.2 on 2022-05-31 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0021_alter_document_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cargo',
            name='value',
        ),
        migrations.RemoveField(
            model_name='transit',
            name='insurance',
        ),
        migrations.RemoveField(
            model_name='transit',
            name='value',
        ),
        migrations.AddField(
            model_name='order',
            name='insurance',
            field=models.BooleanField(default=False, verbose_name='Страхование'),
        ),
        migrations.AddField(
            model_name='order',
            name='value',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Заявленная стоимость'),
        ),
    ]
