# Generated by Django 4.0.2 on 2022-06-01 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0023_remove_cargo_currency_order_currency'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TransitStatus',
        ),
    ]
