# Generated by Django 4.0.2 on 2022-04-16 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0024_order_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transit',
            name='weight_volume',
        ),
        migrations.AddField(
            model_name='cargo',
            name='volume_weight',
            field=models.FloatField(default=0, verbose_name='Объемный вес'),
        ),
    ]
