# Generated by Django 4.0.2 on 2022-06-01 11:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0025_alter_order_options_alter_transit_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transit',
            options={'ordering': ['created_at'], 'permissions': [('view_all_transits', 'Can view all transits')], 'verbose_name': 'перевозка', 'verbose_name_plural': 'перевозки'},
        ),
        migrations.AddField(
            model_name='transit',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
