# Generated by Django 4.0.2 on 2022-04-18 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0025_remove_transit_weight_volume_cargo_volume_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='transit',
            name='from_date_fact',
            field=models.DateField(blank=True, null=True, verbose_name='Фактическая дата отправки'),
        ),
        migrations.AddField(
            model_name='transit',
            name='from_date_plan',
            field=models.DateField(blank=True, null=True, verbose_name='Плановая дата отправки'),
        ),
        migrations.AddField(
            model_name='transit',
            name='to_date_fact',
            field=models.DateField(blank=True, null=True, verbose_name='Фактическая дата доставки'),
        ),
        migrations.AddField(
            model_name='transit',
            name='to_date_plan',
            field=models.DateField(blank=True, null=True, verbose_name='Плановая дата доставки'),
        ),
    ]
