# Generated by Django 4.0.2 on 2022-04-18 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0026_transit_from_date_fact_transit_from_date_plan_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='from_date_fact',
            field=models.DateField(blank=True, null=True, verbose_name='Фактическая дата отправки'),
        ),
        migrations.AddField(
            model_name='order',
            name='from_date_plan',
            field=models.DateField(blank=True, null=True, verbose_name='Плановая дата отправки'),
        ),
        migrations.AddField(
            model_name='order',
            name='to_date_fact',
            field=models.DateField(blank=True, null=True, verbose_name='Фактическая дата доставки'),
        ),
        migrations.AddField(
            model_name='order',
            name='to_date_plan',
            field=models.DateField(blank=True, null=True, verbose_name='Плановая дата доставки'),
        ),
    ]
