# Generated by Django 4.0.2 on 2022-04-21 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0027_order_from_date_fact_order_from_date_plan_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transit',
            name='sub_number',
            field=models.CharField(blank=True, db_index=True, default='', max_length=255, verbose_name='Субномер'),
        ),
        migrations.AlterField(
            model_name='transithistory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Время'),
        ),
    ]
