# Generated by Django 4.0.2 on 2022-05-05 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0028_alter_transit_sub_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cargo',
            name='weight',
            field=models.FloatField(default=0, verbose_name='Вес'),
        ),
    ]
