# Generated by Django 4.0.2 on 2022-06-02 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0030_transit_currency_transit_value'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='currency',
        ),
        migrations.AlterField(
            model_name='cargo',
            name='package_type',
            field=models.CharField(choices=[('pile', 'Навалом'), ('cardboard_box', 'Картонная коробка'), ('pallet', 'Паллет'), ('pack', 'Пачка'), ('bag', 'Мешок'), ('big_bag', 'Биг бэг'), ('wooden_box', 'Деревянный ящик'), ('barrel', 'Бочка'), ('roll', 'Рулон'), ('euroocube', 'Еврокуб'), ('coil', 'Катушка'), ('bale', 'Кипа'), ('safe_package', 'Сейф-пакет'), ('package', 'Пакет'), ('container', 'Контейнер')], default='cardboard_box', max_length=255, verbose_name='Тип упаковки'),
        ),
        migrations.AlterField(
            model_name='order',
            name='value',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Заявленная стоимость'),
        ),
    ]
