# Generated by Django 4.0.2 on 2022-06-02 18:59

from django.db import migrations, models
import orders.models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0032_alter_cargo_package_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transit',
            name='from_inn',
            field=models.BigIntegerField(validators=[orders.models.inn_validator], verbose_name='ИНН отправителя'),
        ),
    ]
