# Generated by Django 4.0.2 on 2022-06-02 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0034_transitsegment_taxes_alter_transit_to_inn'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='taxes',
            field=models.IntegerField(blank=True, choices=[(None, 'Без НДС'), (0, '0%'), (20, '20%')], default=20, null=True, verbose_name='НДС'),
        ),
    ]
