# Generated by Django 4.0.2 on 2022-06-02 20:51

from django.db import migrations, models
import orders.models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0035_order_taxes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transit',
            name='to_inn',
            field=models.BigIntegerField(blank=True, null=True, validators=[orders.models.inn_validator], verbose_name='ИНН получателя'),
        ),
    ]
