# Generated by Django 4.0.2 on 2022-06-07 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0040_alter_cargo_package_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='transitsegment',
            name='tracking_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата транспортного документа'),
        ),
    ]
