# Generated by Django 4.0.2 on 2022-06-07 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0041_transitsegment_tracking_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cargo',
            name='package_type',
            field=models.CharField(choices=[('no_package', 'Без упаковки'), ('wooden_box', 'Деревянный ящик'), ('cardboard_box', 'Картонная коробка'), ('pallet', 'Паллет'), ('envelope', 'Конверт'), ('pile', 'Навалом'), ('pack', 'Пачка'), ('bag', 'Мешок'), ('bucket', 'Ведро'), ('big_bag', 'Биг бэг'), ('barrel', 'Бочка'), ('roll', 'Рулон'), ('euroocube', 'Еврокуб'), ('coil', 'Катушка'), ('bale', 'Кипа'), ('safe_package', 'Сейф-пакет'), ('package', 'Пакет'), ('container', 'Контейнер')], default='no_package', max_length=255, verbose_name='Тип упаковки'),
        ),
    ]
