# Generated by Django 4.0.2 on 2022-06-14 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0047_alter_transit_currency_alter_transitsegment_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cargo',
            name='quantity',
            field=models.IntegerField(default=1, verbose_name='Кол-во мест'),
        ),
        migrations.AlterField(
            model_name='cargo',
            name='volume_weight',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Объемный вес, кг'),
        ),
        migrations.AlterField(
            model_name='cargo',
            name='weight',
            field=models.FloatField(default=0, verbose_name='Вес, кг'),
        ),
    ]
