# Generated by Django 4.0.2 on 2022-06-14 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0049_remove_cargo_volume_weight_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='currency_rate',
            field=models.FloatField(blank=True, default=1, null=True, verbose_name='Курс страховой валюты'),
        ),
        migrations.AddField(
            model_name='order',
            name='insurance_currency',
            field=models.CharField(choices=[('RUB', 'RUB'), ('USD', 'USD'), ('EUR', 'EUR'), ('GBP', 'GBP')], default='RUB', max_length=3, verbose_name='Валюта страхования'),
        ),
        migrations.AddField(
            model_name='order',
            name='sum_insured_coeff',
            field=models.FloatField(choices=[(1, '100%'), (1.1, '110%')], default=1, verbose_name='Коэффициент страховой суммы'),
        ),
        migrations.AddField(
            model_name='transit',
            name='insurance_premium',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Страховая премия'),
        ),
        migrations.AddField(
            model_name='transit',
            name='sum_insured',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Страховая сумма'),
        ),
    ]
