# Generated by Django 4.0.2 on 2022-06-14 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0050_order_currency_rate_order_insurance_currency_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='currency_rate',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Курс страховой валюты'),
        ),
    ]
