# Generated by Django 4.0.2 on 2022-06-17 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0051_alter_order_currency_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='insurance_currency',
            field=models.CharField(blank=True, choices=[('RUB', 'RUB'), ('USD', 'USD'), ('EUR', 'EUR'), ('GBP', 'GBP')], default='RUB', max_length=3, verbose_name='Валюта страхования'),
        ),
        migrations.AlterField(
            model_name='order',
            name='sum_insured_coeff',
            field=models.FloatField(blank=True, choices=[(1, '100%'), (1.1, '110%')], default=1, verbose_name='Коэффициент страховой суммы'),
        ),
    ]
