# Generated by Django 4.0.2 on 2022-07-05 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0058_alter_transit_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cargo',
            name='package_type',
            field=models.CharField(choices=[('wooden_box', 'Деревянный ящик'), ('cardboard_box', 'Картонная коробка'), ('no_package', 'Без упаковки'), ('envelope', 'Конверт'), ('container', 'Контейнер'), ('package', 'Пакет'), ('pallet', 'Паллет'), ('bag', 'Мешок'), ('barrel', 'Бочка'), ('bucket', 'Ведро'), ('roll', 'Рулон'), ('pile', 'Навалом'), ('pack', 'Пачка'), ('big_bag', 'Биг бэг'), ('euroocube', 'Еврокуб'), ('coil', 'Катушка'), ('bale', 'Кипа'), ('safe_package', 'Сейф-пакет')], default='wooden_box', max_length=255, verbose_name='Тип упаковки'),
        ),
    ]
