# Generated by Django 4.0.2 on 2022-07-15 10:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_auth', '0009_alter_contact_cp_alter_contact_phone'),
        ('orders', '0060_transit_from_contacts_transit_receiver_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transit',
            name='receiver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='received_transits', to='app_auth.counterparty', verbose_name='Получатель'),
        ),
    ]
