# Generated by Django 4.0.2 on 2022-08-10 15:53

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import orders.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app_auth', '0019_counterparty_contractor_alter_counterparty_client_and_more'),
        ('orders', '0066_alter_order_auditors'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-created_at'], 'permissions': [('view_all_orders', 'Can view all orders')], 'verbose_name': 'входящее поручение', 'verbose_name_plural': 'входящие поручения'},
        ),
        migrations.AddField(
            model_name='transitsegment',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='segments', to='orders.order'),
        ),
        migrations.AddField(
            model_name='transitsegment',
            name='ordering_num',
            field=models.IntegerField(blank=True, null=True, verbose_name='Порядковый номер'),
        ),
        migrations.AddField(
            model_name='transitsegment',
            name='receiver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='received_segments', to='app_auth.counterparty', verbose_name='Получатель'),
        ),
        migrations.AddField(
            model_name='transitsegment',
            name='sender',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sent_segments', to='app_auth.counterparty', verbose_name='Отправитель'),
        ),
        migrations.CreateModel(
            name='ExtOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='Время создания')),
                ('last_update', models.DateTimeField(auto_now=True, verbose_name='Время последнего изменения')),
                ('number', models.CharField(max_length=255, verbose_name='Номер поручения')),
                ('date', models.DateField(verbose_name='Дата поручения')),
                ('contract', models.CharField(blank=True, max_length=255, null=True, verbose_name='Договор')),
                ('price_carrier', models.FloatField(default=0, verbose_name='Закупочная цена')),
                ('taxes', models.IntegerField(blank=True, choices=[(None, 'Без НДС'), (0, '0%'), (20, '20%')], default=20, null=True, verbose_name='НДС')),
                ('currency', models.CharField(choices=[('RUB', 'RUB'), ('USD', 'USD'), ('EUR', 'EUR'), ('GBP', 'GBP')], default='RUB', max_length=3, verbose_name='Валюта')),
                ('from_addr', models.CharField(max_length=255, verbose_name='Адрес забора груза')),
                ('from_date_wanted', models.DateField(blank=True, null=True, verbose_name='Дата готовности груза')),
                ('from_date_plan', models.DateField(blank=True, null=True, verbose_name='Плановая дата забора груза')),
                ('from_date_fact', models.DateField(blank=True, null=True, verbose_name='Фактическая дата забора груза')),
                ('to_addr', models.CharField(max_length=255, verbose_name='Адрес доставки')),
                ('to_date_wanted', models.DateField(blank=True, null=True, verbose_name='Желаемая дата доставки')),
                ('to_date_plan', models.DateField(blank=True, null=True, verbose_name='Плановая дата доставки')),
                ('to_date_fact', models.DateField(blank=True, null=True, verbose_name='Фактическая дата доставки')),
                ('status', models.CharField(choices=[('new', 'Новое'), ('pre_process', 'Принято в работу'), ('rejected', 'Аннулировано'), ('in_progress', 'На исполнении'), ('delivered', 'Выполнено'), ('bargain', 'Согласование ставок'), ('awaiting_docs', 'жидание оригиналов документов'), ('completed', 'Завершено')], db_index=True, default='new', max_length=50, verbose_name='Статус поручения')),
                ('contractor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ext_orders', to='app_auth.contractor', verbose_name='Перевозчик')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ext_orders', to='orders.order')),
                ('receiver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='received_ext_orders', to='app_auth.counterparty', verbose_name='Получатель')),
                ('sender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sent_ext_orders', to='app_auth.counterparty', verbose_name='Отправитель')),
                ('transit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ext_orders', to='orders.transit')),
            ],
            options={
                'verbose_name': 'Исходящее поручение',
                'verbose_name_plural': 'Исходящие поручения',
                'permissions': [('view_all_ext_orders', 'Can view all external orders')],
            },
            bases=(models.Model, orders.models.RecalcMixin),
        ),
        migrations.CreateModel(
            name='AutoTransit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='Время создания')),
                ('last_update', models.DateTimeField(auto_now=True, verbose_name='Время последнего изменения')),
                ('driver_full_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='ФИО')),
                ('driver_birth_date', models.DateField(blank=True, null=True, verbose_name='Дата рождения')),
                ('driver_passport_num', models.CharField(blank=True, max_length=255, null=True, verbose_name='Серия/номер')),
                ('driver_passport_date', models.DateField(blank=True, null=True, verbose_name='Дата выдачи')),
                ('driver_passport_issuer', models.CharField(blank=True, max_length=255, null=True, verbose_name='Кем выдан')),
                ('driver_entity', models.CharField(blank=True, max_length=255, null=True, verbose_name='Гражданство')),
                ('driver_legal_addr', models.CharField(blank=True, max_length=255, null=True, verbose_name='Адрес регистрации')),
                ('driver_license_num', models.CharField(blank=True, max_length=255, null=True, verbose_name='Номер водительского удостоверения')),
                ('auto_model', models.CharField(blank=True, max_length=255, null=True, verbose_name='Марка ТС')),
                ('auto_num', models.CharField(blank=True, max_length=255, null=True, verbose_name='Гос. номер ТС')),
                ('segment', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='auto', to='orders.transitsegment')),
            ],
        ),
        migrations.CreateModel(
            name='AeroTransit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='Время создания')),
                ('last_update', models.DateTimeField(auto_now=True, verbose_name='Время последнего изменения')),
                ('awb_num', models.CharField(blank=True, max_length=255, null=True, verbose_name='Номер авианакладной')),
                ('awb_date', models.DateField(blank=True, null=True, verbose_name='Дата авианакладной')),
                ('awb_weight', models.FloatField(blank=True, null=True, verbose_name='Оплачиваемый вес, кг')),
                ('awb_quantity', models.IntegerField(blank=True, null=True, verbose_name='Кол-во мест (по авианакладной)')),
                ('cargo_info', models.TextField(blank=True, null=True, verbose_name='Информация по обработке груза')),
                ('segment', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='aero', to='orders.transitsegment')),
            ],
        ),
        migrations.AddField(
            model_name='transitsegment',
            name='ext_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='segments', to='orders.extorder', verbose_name='Исходящее поручение'),
        ),
    ]
