# Generated by Django 4.0.2 on 2022-08-22 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0067_alter_order_options_transitsegment_order_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aerotransit',
            name='awb_weight',
            field=models.FloatField(blank=True, null=True, verbose_name='Оплачиваемый вес, кг (по авианакладной)'),
        ),
    ]
