# Generated by Django 4.0.2 on 2022-09-28 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_auth', '0020_alter_counterparty_client_and_more'),
        ('orders', '0072_order_cargo_name_order_cargo_origin'),
    ]

    operations = [
        migrations.AddField(
            model_name='extorder',
            name='from_contacts',
            field=models.ManyToManyField(related_name='cnt_sent_ext_orders', to='app_auth.Contact', verbose_name='Контактные лица'),
        ),
        migrations.AddField(
            model_name='extorder',
            name='to_contacts',
            field=models.ManyToManyField(related_name='cnt_received_ext_orders', to='app_auth.Contact', verbose_name='Контактные лица'),
        ),
    ]
