# Generated by Django 4.0.2 on 2022-09-30 15:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_auth', '0021_counterparty_admin'),
        ('orders', '0074_alter_extorder_options_alter_transitsegment_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transitsegment',
            name='from_addr',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Адрес забора груза'),
        ),
        migrations.AlterField(
            model_name='transitsegment',
            name='receiver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='received_segments', to='app_auth.counterparty', verbose_name='Получатель'),
        ),
        migrations.AlterField(
            model_name='transitsegment',
            name='sender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sent_segments', to='app_auth.counterparty', verbose_name='Отправитель'),
        ),
        migrations.AlterField(
            model_name='transitsegment',
            name='to_addr',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Адрес доставки'),
        ),
    ]
