# Generated by Django 4.0.2 on 2022-09-30 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0075_alter_transitsegment_from_addr_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cargo',
            name='height',
            field=models.FloatField(verbose_name='Высота'),
        ),
        migrations.AlterField(
            model_name='cargo',
            name='length',
            field=models.FloatField(verbose_name='Длина'),
        ),
        migrations.AlterField(
            model_name='cargo',
            name='weight',
            field=models.FloatField(verbose_name='Вес, кг'),
        ),
        migrations.AlterField(
            model_name='cargo',
            name='width',
            field=models.FloatField(verbose_name='Ширина'),
        ),
    ]
