# Generated by Django 4.0.2 on 2022-09-30 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0076_alter_cargo_height_alter_cargo_length_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cargo',
            name='quantity',
            field=models.IntegerField(verbose_name='Кол-во мест'),
        ),
    ]
