# Generated by Django 4.0.2 on 2022-10-18 15:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0077_alter_cargo_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extorder',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Дата поручения'),
        ),
        migrations.AlterField(
            model_name='extorder',
            name='status',
            field=models.CharField(choices=[('new', 'Новое'), ('pre_process', 'Принято в работу'), ('rejected', 'Аннулировано'), ('in_progress', 'На исполнении'), ('delivered', 'Выполнено'), ('bargain', 'Согласование ставок'), ('awaiting_docs', 'Ожидание оригиналов документов'), ('completed', 'Завершено')], db_index=True, default='new', max_length=50, verbose_name='Статус поручения'),
        ),
    ]
