# Generated by Django 4.0.8 on 2022-11-15 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0080_remove_transit_sub_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='transitsegment',
            name='weight_brut',
            field=models.FloatField(default=0, verbose_name='Вес брутто, кг'),
        ),
        migrations.AlterField(
            model_name='transitsegment',
            name='weight_payed',
            field=models.FloatField(default=0, verbose_name='Оплачиваемый вес, кг'),
        ),
    ]
