# Generated by Django 4.0.8 on 2022-11-17 10:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_auth', '0024_contractorcontract_clientcontract'),
        ('orders', '0082_alter_order_client_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='extorder',
            name='contract_fk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='app_auth.contractorcontract', verbose_name='Договор'),
        ),
        migrations.AddField(
            model_name='order',
            name='contract_fk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='app_auth.clientcontract', verbose_name='Договор'),
        ),
    ]
