# Generated by Django 4.0.8 on 2022-11-18 13:57

from django.db import migrations, models
import django.db.models.deletion


def fill_fk(apps, schema_editor):
    Order = apps.get_model('orders', 'Order')
    ExtOrder = apps.get_model('orders', 'ExtOrder')
    ClientContract = apps.get_model('app_auth', 'ClientContract')
    ContractorContract = apps.get_model('app_auth', 'ContractorContract')

    for i in Order.objects.all():
        i.contract_fk = ClientContract.objects.get_or_create(
            number=i.client.contract,
            sign_date=i.client.contract_sign_date,
            expiration_date=i.client.contract_expiration_date
        )

    for i in ExtOrder.objects.all():
        i.contract_fk = ContractorContract.objects.get_or_create(
            number=i.contractor.contract,
            sign_date=i.contractor.contract_sign_date,
            expiration_date=i.contractor.contract_expiration_date
        )


class Migration(migrations.Migration):

    dependencies = [
        ('app_auth', '0024_contractorcontract_clientcontract'),
        ('orders', '0082_alter_order_client_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='extorder',
            name='contract_fk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='app_auth.contractorcontract', verbose_name='Договор'),
        ),
        migrations.AddField(
            model_name='order',
            name='contract_fk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='app_auth.clientcontract', verbose_name='Договор'),
        ),
        migrations.RunPython(fill_fk, reverse_code=migrations.RunPython.noop)
    ]
