# Generated by Django 4.0.8 on 2022-11-17 10:53

from django.db import migrations


def apply_client_contracts(apps, schema_editor):
    Order = apps.get_model('orders', 'Order')
    ClientContract = apps.get_model('app_auth', 'ClientContract')
    for order in Order.objects.all():
        order.contract_fk, created = ClientContract.objects.get_or_create(
            number=order.client.contract,
            sign_date=order.client.contract_sign_date,
            expiration_date=order.client.contract_expiration_date,
            client=order.client
        )
        order.save()


def apply_contractor_contracts(apps, schema_editor):
    ExtOrder = apps.get_model('orders', 'ExtOrder')
    ContractorContract = apps.get_model('app_auth', 'ContractorContract')
    for ext_order in ExtOrder.objects.all():
        ext_order.contract_fk, created = ContractorContract.objects.get_or_create(
            number=ext_order.contractor.contract,
            sign_date=ext_order.contractor.contract_sign_date,
            expiration_date=ext_order.contractor.contract_expiration_date,
            contractor=ext_order.contractor
        )
        ext_order.save()


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0083_extorder_contract_fk_order_contract_fk'),
    ]

    operations = [
        migrations.RunPython(apply_client_contracts, reverse_code=migrations.RunPython.noop),
        migrations.RunPython(apply_contractor_contracts, reverse_code=migrations.RunPython.noop)
    ]
