# Generated by Django 4.0.8 on 2022-11-18 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_auth', '0024_contractorcontract_clientcontract'),
        ('orders', '0083_extorder_contract_fk_order_contract_fk'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extorder',
            name='contract',
        ),
        migrations.RemoveField(
            model_name='order',
            name='contract',
        ),
        migrations.RenameField(
            model_name='extorder',
            old_name='contract_fk',
            new_name='contract'
        ),
        migrations.RenameField(
            model_name='order',
            old_name='contract_fk',
            new_name='contract'
        ),
    ]
