# Generated by Django 4.0.8 on 2022-11-17 11:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_auth', '0025_remove_client_contract_and_more'),
        ('orders', '0084_auto_20221117_1053'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extorder',
            name='contract',
        ),
        migrations.RenameField(
            model_name='extorder',
            old_name='contract_fk',
            new_name='contract'
        ),
        migrations.RemoveField(
            model_name='order',
            name='contract',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='contract_fk',
            new_name='contract'
        )
    ]
