# Generated by Django 4.0.8 on 2022-11-23 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0084_remove_extorder_contract_fk_remove_order_contract_fk_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='extorder',
            name='other',
            field=models.TextField(blank=True, null=True, verbose_name='Иное'),
        ),
    ]
