# Generated by Django 4.0.8 on 2022-11-17 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0085_remove_extorder_contract_fk_remove_order_contract_fk_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extorder',
            name='contract',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='order',
            name='contract',
            field=models.IntegerField(),
        ),
    ]
