# Generated by Django 4.0.8 on 2022-11-17 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0086_alter_extorder_contract_alter_order_contract'),
        ('app_auth', '0027_alter_clientcontract_id_alter_clientcontract_u_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='extorder',
            old_name='contract',
            new_name='contract_old',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='contract',
            new_name='contract_old',
        ),
    ]
