# Generated by Django 4.0.8 on 2022-11-17 17:53

from django.db import migrations, models
import django.db.models.deletion


def copy_extorder_uuids(apps, schema_editor):
    ExtOrder = apps.get_model('orders', 'ExtOrder')
    ContractorContract = apps.get_model('app_auth', 'ContractorContract')
    contract_uuid = ContractorContract.objects.filter(id=models.OuterRef('contract_old')).values_list('u_id')[:1]
    ExtOrder.objects.update(contract=models.Subquery(contract_uuid))


def copy_order_uuids(apps, schema_editor):
    Order = apps.get_model('orders', 'Order')
    ClientContract = apps.get_model('app_auth', 'ClientContract')
    contract_uuid = ClientContract.objects.filter(id=models.OuterRef('contract_old')).values_list('u_id')[:1]
    Order.objects.update(contract=models.Subquery(contract_uuid))


class Migration(migrations.Migration):

    dependencies = [
        ('app_auth', '0027_alter_clientcontract_id_alter_clientcontract_u_id_and_more'),
        ('orders', '0087_rename_contract_extorder_contract_old_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='extorder',
            name='contract',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='app_auth.contractorcontract', verbose_name='Договор'),
        ),
        migrations.RunPython(
            copy_extorder_uuids,
            reverse_code=migrations.RunPython.noop
        ),
        migrations.AddField(
            model_name='order',
            name='contract',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='app_auth.clientcontract', verbose_name='Договор'),
        ),
        migrations.RunPython(
            copy_order_uuids,
            reverse_code=migrations.RunPython.noop
        ),
    ]
