# Generated by Django 4.0.8 on 2022-11-23 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0087_extorder_give_to_extorder_take_from'),
    ]

    operations = [
        migrations.AddField(
            model_name='transit',
            name='from_date_wanted',
            field=models.DateField(blank=True, null=True, verbose_name='Дата готовности груза'),
        ),
        migrations.AddField(
            model_name='transit',
            name='to_date_wanted',
            field=models.DateField(blank=True, null=True, verbose_name='Желаемая дата доставки'),
        ),
    ]
