# Generated by Django 4.0.8 on 2022-11-17 18:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_auth', '0028_remove_clientcontract_id_and_more'),
        ('orders', '0088_extorder_contract_order_contract'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extorder',
            name='contract_old',
        ),
        migrations.RemoveField(
            model_name='order',
            name='contract_old',
        ),
        migrations.AlterField(
            model_name='extorder',
            name='contract',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app_auth.contractorcontract', verbose_name='Договор', null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='contract',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app_auth.clientcontract', verbose_name='Договор', null=True),
        ),
    ]
