# Generated by Django 4.0.8 on 2022-12-05 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0091_transit_price_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transit',
            name='price',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Ставка'),
        ),
    ]
