# Generated by Django 4.0.8 on 2022-12-06 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0092_alter_transit_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='bill_number',
        ),
        migrations.AddField(
            model_name='transit',
            name='bill_number',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Номер счета'),
        ),
    ]
