# Generated by Django 4.0.8 on 2022-12-07 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0094_transit_weight_payed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transit',
            name='price',
            field=models.FloatField(default=0, verbose_name='Ставка'),
        ),
    ]
