# Generated by Django 4.0.8 on 2022-12-14 13:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_auth', '0025_remove_client_contract_and_more'),
        ('orders', '0095_alter_transit_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='extorder',
            name='contractor_employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='executing_orders', to=settings.AUTH_USER_MODEL, verbose_name='Сотркдник Перевозчика'),
        ),
        migrations.AddField(
            model_name='extorder',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ext_orders', to=settings.AUTH_USER_MODEL, verbose_name='Менеджер'),
        ),
        migrations.AlterField(
            model_name='extorder',
            name='contract',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='app_auth.contractorcontract', verbose_name='Договор'),
        ),
        migrations.AlterField(
            model_name='extorder',
            name='contractor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ext_orders', to='app_auth.contractor', verbose_name='Перевозчик'),
        ),
    ]
