# Generated by Django 4.0.8 on 2022-12-15 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0096_extorder_contractor_employee_extorder_manager_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transitsegment',
            options={'ordering': ['ext_order', 'ordering_num'], 'verbose_name': 'плечо перевозки', 'verbose_name_plural': 'плечи перевозки'},
        ),
        migrations.AddField(
            model_name='order',
            name='insurance_policy_number',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='№ полиса'),
        ),
        migrations.AddField(
            model_name='order',
            name='insurance_premium_coeff',
            field=models.FloatField(default=0.00055, verbose_name='Коэффициент страховой премии'),
        ),
    ]
