# Generated by Django 4.0.8 on 2022-12-28 11:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0097_alter_transitsegment_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extorder',
            name='contractor_employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='executing_orders', to=settings.AUTH_USER_MODEL, verbose_name='Сотрудник Перевозчика'),
        ),
    ]
