# Generated by Django 4.0.8 on 2023-01-17 16:47

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0098_alter_extorder_contractor_employee'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='Время создания')),
                ('last_update', models.DateTimeField(auto_now=True, verbose_name='Время последнего изменения')),
                ('ext_order', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='orders.extorder', verbose_name='')),
                ('segment', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='transport', to='orders.transitsegment', verbose_name='')),
            ],
        ),
    ]
