# Generated by Django 4.0.2 on 2022-05-19 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_auth', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'permissions': [('view_all_clients', 'Can view all clients')], 'verbose_name': 'клиент', 'verbose_name_plural': 'клиенты'},
        ),
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name': 'контакт', 'verbose_name_plural': 'контакты'},
        ),
        migrations.AlterModelOptions(
            name='contractor',
            options={'verbose_name': 'подрядчик', 'verbose_name_plural': 'подрядчики'},
        ),
        migrations.AlterModelOptions(
            name='counterparty',
            options={'verbose_name': 'контрагент клиента', 'verbose_name_plural': 'контрагенты клиента'},
        ),
        migrations.AlterField(
            model_name='client',
            name='fact_address',
            field=models.CharField(max_length=255, verbose_name='Факт. адрес'),
        ),
        migrations.AlterField(
            model_name='client',
            name='inn',
            field=models.IntegerField(db_index=True, verbose_name='ИНН'),
        ),
        migrations.AlterField(
            model_name='client',
            name='kpp',
            field=models.IntegerField(db_index=True, verbose_name='КПП'),
        ),
        migrations.AlterField(
            model_name='client',
            name='legal_address',
            field=models.CharField(max_length=255, verbose_name='Юр. адрес'),
        ),
        migrations.AlterField(
            model_name='client',
            name='num_prefix',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='Префикс номера поручения'),
        ),
        migrations.AlterField(
            model_name='contractor',
            name='fact_address',
            field=models.CharField(max_length=255, verbose_name='Факт. адрес'),
        ),
        migrations.AlterField(
            model_name='contractor',
            name='inn',
            field=models.IntegerField(db_index=True, verbose_name='ИНН'),
        ),
        migrations.AlterField(
            model_name='contractor',
            name='kpp',
            field=models.IntegerField(db_index=True, verbose_name='КПП'),
        ),
        migrations.AlterField(
            model_name='contractor',
            name='legal_address',
            field=models.CharField(max_length=255, verbose_name='Юр. адрес'),
        ),
        migrations.AlterField(
            model_name='counterparty',
            name='fact_address',
            field=models.CharField(max_length=255, verbose_name='Факт. адрес'),
        ),
        migrations.AlterField(
            model_name='counterparty',
            name='inn',
            field=models.IntegerField(db_index=True, verbose_name='ИНН'),
        ),
        migrations.AlterField(
            model_name='counterparty',
            name='kpp',
            field=models.IntegerField(db_index=True, verbose_name='КПП'),
        ),
        migrations.AlterField(
            model_name='counterparty',
            name='legal_address',
            field=models.CharField(max_length=255, verbose_name='Юр. адрес'),
        ),
    ]
