# Generated by Django 4.0.2 on 2022-05-30 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_auth', '0002_alter_client_options_alter_contact_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='num_prefix',
            field=models.CharField(default='HUI', max_length=5, verbose_name='Префикс номера поручения'),
            preserve_default=False,
        ),
    ]
