# Generated by Django 4.0.2 on 2022-06-02 19:43

import app_auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_auth', '0006_alter_client_kpp_alter_contractor_kpp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='inn',
            field=models.BigIntegerField(db_index=True, validators=[app_auth.models.inn_validator], verbose_name='ИНН'),
        ),
        migrations.AlterField(
            model_name='contractor',
            name='inn',
            field=models.BigIntegerField(db_index=True, validators=[app_auth.models.inn_validator], verbose_name='ИНН'),
        ),
        migrations.AlterField(
            model_name='counterparty',
            name='inn',
            field=models.BigIntegerField(db_index=True, validators=[app_auth.models.inn_validator], verbose_name='ИНН'),
        ),
    ]
