# Generated by Django 4.0.2 on 2022-07-20 16:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app_auth', '0009_alter_contact_cp_alter_contact_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportParams',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Имя отчета')),
                ('_fields', models.TextField(verbose_name='Поля отчета')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
    ]
