# Generated by Django 4.0.2 on 2022-08-03 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_auth', '0015_remove_reportparams_report_class'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportparams',
            name='merge_segments',
            field=models.BooleanField(default=False, verbose_name='Группировать по перевозчику'),
        ),
    ]
