# Generated by Django 4.0.2 on 2022-08-08 12:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_auth', '0016_reportparams_merge_segments'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='carrier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='app_auth.contractor', verbose_name='подрядчик'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('manager', 'Менеджер'), ('client_simple', 'Заказчик (обычный)'), ('client_advanced', 'Заказчик (расширенный)'), ('auditor_simple', 'Аудитор (обычный)'), ('auditor_advanced', 'Аудитор (расширенный)'), ('carrier_simple', 'Подрядчик (обычный)'), ('carrier_advanced', 'Подрядчик (расширенный)')], default='manager', max_length=25, verbose_name='тип пользователя'),
        ),
    ]
