# Generated by Django 4.0.2 on 2022-09-19 18:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_auth', '0019_counterparty_contractor_alter_counterparty_client_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='counterparty',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='counterparties', to='app_auth.client'),
        ),
        migrations.AlterField(
            model_name='counterparty',
            name='contractor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='counterparties', to='app_auth.contractor'),
        ),
    ]
