# Generated by Django 4.0.8 on 2022-11-16 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_auth', '0022_alter_client_num_prefix'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditor',
            name='full_name',
            field=models.CharField(default='', max_length=255, verbose_name='Полное наименование'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='auditor',
            name='ogrn',
            field=models.CharField(blank=True, db_index=True, max_length=15, null=True, verbose_name='ОГРН'),
        ),
        migrations.AddField(
            model_name='client',
            name='full_name',
            field=models.CharField(default='', max_length=255, verbose_name='Полное наименование'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='client',
            name='ogrn',
            field=models.CharField(blank=True, db_index=True, max_length=15, null=True, verbose_name='ОГРН'),
        ),
        migrations.AddField(
            model_name='contractor',
            name='full_name',
            field=models.CharField(default='', max_length=255, verbose_name='Полное наименование'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contractor',
            name='ogrn',
            field=models.CharField(blank=True, db_index=True, max_length=15, null=True, verbose_name='ОГРН'),
        ),
        migrations.AddField(
            model_name='counterparty',
            name='full_name',
            field=models.CharField(default='', max_length=255, verbose_name='Полное наименование'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='counterparty',
            name='ogrn',
            field=models.CharField(blank=True, db_index=True, max_length=15, null=True, verbose_name='ОГРН'),
        ),
    ]
