# Generated by Django 4.1.7 on 2023-02-25 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_auth', '0027_contractorcontract_bank_contractorcontract_bik_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractor',
            name='accountant',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Бухгалтер'),
        ),
        migrations.AddField(
            model_name='contractor',
            name='head',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Руководитель'),
        ),
    ]
