# Generated by Django 4.1.7 on 2023-05-19 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_auth', '0029_auditor_email_client_email_contractor_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditor',
            name='email',
            field=models.CharField(max_length=50, null=True, verbose_name='Почта для рассылки'),
        ),
        migrations.AlterField(
            model_name='client',
            name='email',
            field=models.CharField(max_length=50, null=True, verbose_name='Почта для рассылки'),
        ),
        migrations.AlterField(
            model_name='contractor',
            name='email',
            field=models.CharField(max_length=50, null=True, verbose_name='Почта для рассылки'),
        ),
        migrations.AlterField(
            model_name='counterparty',
            name='email',
            field=models.CharField(max_length=50, null=True, verbose_name='Почта для рассылки'),
        ),
    ]
