# Generated by Django 4.1.10 on 2023-07-31 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_auth', '0031_alter_auditor_email_alter_client_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientcontract',
            name='currency',
            field=models.CharField(choices=[('RUB', 'RUB'), ('USD', 'USD'), ('EUR', 'EUR'), ('GBP', 'GBP')], default='RUB', max_length=3, verbose_name='Валюта договора'),
        ),
        migrations.AddField(
            model_name='clientcontract',
            name='current_sum',
            field=models.FloatField(default=0, verbose_name='Текущий остаток'),
        ),
        migrations.AddField(
            model_name='clientcontract',
            name='full_sum',
            field=models.FloatField(default=0, verbose_name='Сумма договора'),
        ),
        migrations.AddField(
            model_name='clientcontract',
            name='initial_sum',
            field=models.FloatField(default=0, verbose_name='Начальный остаток'),
        ),
        migrations.AddField(
            model_name='contractorcontract',
            name='currency',
            field=models.CharField(choices=[('RUB', 'RUB'), ('USD', 'USD'), ('EUR', 'EUR'), ('GBP', 'GBP')], default='RUB', max_length=3, verbose_name='Валюта договора'),
        ),
        migrations.AddField(
            model_name='contractorcontract',
            name='current_sum',
            field=models.FloatField(default=0, verbose_name='Текущий остаток'),
        ),
        migrations.AddField(
            model_name='contractorcontract',
            name='full_sum',
            field=models.FloatField(default=0, verbose_name='Сумма договора'),
        ),
        migrations.AddField(
            model_name='contractorcontract',
            name='initial_sum',
            field=models.FloatField(default=0, verbose_name='Начальный остаток'),
        ),
    ]
