# Generated by Django 4.1.10 on 2023-08-03 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_auth', '0033_currencyrate'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='currencyrate',
            options={'ordering': ['date'], 'verbose_name': 'курс валют', 'verbose_name_plural': 'курсы валют'},
        ),
    ]
