# Generated by Django 4.1.10 on 2023-08-25 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_auth', '0034_alter_currencyrate_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='boss',
            field=models.BooleanField(default=False, verbose_name='Руководящее лицо'),
        ),
    ]
