# Generated by Django 4.1.11 on 2023-09-10 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_auth', '0036_currencyrate_inr'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientcontract',
            name='add_agreement_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата доп. соглашения'),
        ),
        migrations.AddField(
            model_name='clientcontract',
            name='add_agreement_number',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='№ доп. соглашения'),
        ),
        migrations.AddField(
            model_name='clientcontract',
            name='name',
            field=models.CharField(default='', max_length=255, verbose_name='Наименование договора'),
        ),
        migrations.AddField(
            model_name='contractorcontract',
            name='add_agreement_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата доп. соглашения'),
        ),
        migrations.AddField(
            model_name='contractorcontract',
            name='add_agreement_number',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='№ доп. соглашения'),
        ),
        migrations.AddField(
            model_name='contractorcontract',
            name='name',
            field=models.CharField(default='', max_length=255, verbose_name='Наименование договора'),
        ),
    ]
