# Generated by Django 4.1.11 on 2023-09-29 14:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_auth', '0037_clientcontract_add_agreement_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientcontract',
            name='start_date',
            field=models.DateField(default=datetime.date(2020, 1, 1), verbose_name='Дата начала действия договора'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contractorcontract',
            name='start_date',
            field=models.DateField(default=datetime.date(2020, 1, 1), verbose_name='Дата начала действия договора'),
            preserve_default=False,
        ),
    ]
