# Generated by Django 4.1.11 on 2023-10-03 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_auth', '0038_clientcontract_start_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['last_name', 'first_name'], 'permissions': [('view_all_users', 'Can view all users')], 'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
    ]
