# Generated by Django 4.1.13 on 2023-12-04 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_auth', '0039_alter_user_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientcontract',
            name='order_template',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Шаблон ПЭ'),
        ),
        migrations.AddField(
            model_name='clientcontract',
            name='receipt_template',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Шаблон ЭР'),
        ),
    ]
