# Generated by Django 4.1.13 on 2023-12-09 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_auth', '0041_client_order_template_client_receipt_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='order_label',
            field=models.CharField(choices=[('default', 'ПЭ'), ('order', 'Заказ'), ('claim', 'Заявка')], default=('default', 'ПЭ'), max_length=20, verbose_name='Название осн. вх. документа'),
        ),
        migrations.AddField(
            model_name='clientcontract',
            name='order_label',
            field=models.CharField(choices=[('default', 'ПЭ'), ('order', 'Заказ'), ('claim', 'Заявка')], default=('default', 'ПЭ'), max_length=20, verbose_name='Название осн. вх. документа'),
        ),
    ]
