# Generated by Django 4.1.13 on 2023-12-20 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_auth', '0042_client_order_label_clientcontract_order_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractor',
            name='order_label',
            field=models.CharField(choices=[('default', 'ПЭ'), ('order', 'Заказ'), ('claim', 'Заявка')], default=('default', 'ПЭ'), max_length=20, verbose_name='Название осн. вх. документа'),
        ),
        migrations.AddField(
            model_name='contractor',
            name='order_template',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Шаблон ПЭ'),
        ),
        migrations.AddField(
            model_name='contractor',
            name='receipt_template',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Шаблон ЭР'),
        ),
        migrations.AddField(
            model_name='contractorcontract',
            name='order_label',
            field=models.CharField(choices=[('default', 'ПЭ'), ('order', 'Заказ'), ('claim', 'Заявка')], default=('default', 'ПЭ'), max_length=20, verbose_name='Название осн. вх. документа'),
        ),
        migrations.AddField(
            model_name='contractorcontract',
            name='order_template',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Шаблон ПЭ'),
        ),
        migrations.AddField(
            model_name='contractorcontract',
            name='receipt_template',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Шаблон ЭР'),
        ),
    ]
