# Generated by Django 4.1.13 on 2024-01-09 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_auth', '0043_contractor_order_label_contractor_order_template_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='order_label',
            field=models.CharField(choices=[('default', 'ПЭ'), ('order', 'Заказ'), ('claim', 'Заявка')], default='default', max_length=20, verbose_name='Название осн. вх. документа'),
        ),
        migrations.AlterField(
            model_name='clientcontract',
            name='order_label',
            field=models.CharField(choices=[('default', 'ПЭ'), ('order', 'Заказ'), ('claim', 'Заявка')], default='default', max_length=20, verbose_name='Название осн. вх. документа'),
        ),
        migrations.AlterField(
            model_name='contractor',
            name='order_label',
            field=models.CharField(choices=[('default', 'ПЭ'), ('order', 'Заказ'), ('claim', 'Заявка')], default='default', max_length=20, verbose_name='Название осн. вх. документа'),
        ),
        migrations.AlterField(
            model_name='contractorcontract',
            name='order_label',
            field=models.CharField(choices=[('default', 'ПЭ'), ('order', 'Заказ'), ('claim', 'Заявка')], default='default', max_length=20, verbose_name='Название осн. вх. документа'),
        ),
    ]
