# Generated by Django 4.1.13 on 2024-01-29 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_auth', '0046_auditor_created_at_auditor_last_update_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='id_1c',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='clientcontract',
            name='id_1c',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='contractor',
            name='id_1c',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='contractorcontract',
            name='id_1c',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
