# Generated by Django 4.1.13 on 2024-02-05 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_auth', '0047_client_id_1c_clientcontract_id_1c_contractor_id_1c_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='id_1c',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='clientcontract',
            name='id_1c',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='contractor',
            name='id_1c',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='contractorcontract',
            name='id_1c',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
