# Generated by Django 4.1.13 on 2024-02-28 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_auth', '0048_alter_client_id_1c_alter_clientcontract_id_1c_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientcontract',
            name='mark',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Служебная метка'),
        ),
        migrations.AddField(
            model_name='contractorcontract',
            name='mark',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Служебная метка'),
        ),
    ]
