# Generated by Django 4.1.13 on 2024-03-26 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_auth', '0050_alter_clientcontract_currency_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientcontract',
            name='name',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Наименование договора'),
        ),
        migrations.AlterField(
            model_name='contractorcontract',
            name='name',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Наименование договора'),
        ),
    ]
