# Generated by Django 4.1.13 on 2024-05-23 00:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_auth', '0051_alter_clientcontract_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auditor',
            options={'ordering': ('short_name',), 'verbose_name': 'аудитор', 'verbose_name_plural': 'аудиторы'},
        ),
        migrations.AlterModelOptions(
            name='client',
            options={'ordering': ('short_name',), 'permissions': [('view_all_clients', 'Can view all clients')], 'verbose_name': 'клиент', 'verbose_name_plural': 'клиенты'},
        ),
        migrations.AlterModelOptions(
            name='contractor',
            options={'ordering': ('short_name',), 'verbose_name': 'подрядчик', 'verbose_name_plural': 'подрядчики'},
        ),
        migrations.AlterModelOptions(
            name='counterparty',
            options={'ordering': ('short_name',), 'verbose_name': 'контрагент клиента', 'verbose_name_plural': 'контрагенты клиента'},
        ),
    ]
