# Generated by Django 4.0.2 on 2022-05-16 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_order_quantity_order_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='quantity',
            field=models.IntegerField(default=0, verbose_name='Количество мест'),
        ),
        migrations.AlterField(
            model_name='transit',
            name='quantity',
            field=models.IntegerField(default=0, verbose_name='Количество мест'),
        ),
    ]
