# Generated by Django 4.0.2 on 2022-05-19 10:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_auth', '0002_alter_client_options_alter_contact_options_and_more'),
        ('orders', '0011_transit_contract'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cargo',
            options={'verbose_name': 'груз', 'verbose_name_plural': 'грузы'},
        ),
        migrations.AlterModelOptions(
            name='orderhistory',
            options={'ordering': ['created_at'], 'verbose_name': 'элемент истории поручения', 'verbose_name_plural': 'элементы истории поручения'},
        ),
        migrations.AlterModelOptions(
            name='transithistory',
            options={'ordering': ['created_at'], 'verbose_name': 'элемент истории перевозки', 'verbose_name_plural': 'элементы истории перевозки'},
        ),
        migrations.AlterModelOptions(
            name='transitstatus',
            options={'verbose_name': 'статус перевозки', 'verbose_name_plural': 'статусы перевозки'},
        ),
        migrations.AddField(
            model_name='transit',
            name='from_legal_addr',
            field=models.CharField(default='', max_length=255, verbose_name='Юр. адрес'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transit',
            name='to_legal_addr',
            field=models.CharField(default='', max_length=255, verbose_name='Юр. адрес'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transit',
            name='tracking_number',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Номер транспортного документа'),
        ),
        migrations.AlterField(
            model_name='order',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='app_auth.client', verbose_name='Заказчик'),
        ),
        migrations.AlterField(
            model_name='transit',
            name='carrier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transits', to='app_auth.contractor', verbose_name='Перевозчик'),
        ),
        migrations.AlterField(
            model_name='transit',
            name='price',
            field=models.FloatField(default=0, verbose_name='Ставка'),
        ),
        migrations.AlterField(
            model_name='transit',
            name='price_carrier',
            field=models.FloatField(default=0, verbose_name='Закупочная цена'),
        ),
    ]
