# Generated by Django 4.0.2 on 2022-05-23 14:59

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app_auth', '0002_alter_client_options_alter_contact_options_and_more'),
        ('orders', '0012_alter_cargo_options_alter_orderhistory_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transit',
            name='carrier',
        ),
        migrations.RemoveField(
            model_name='transit',
            name='contract',
        ),
        migrations.RemoveField(
            model_name='transit',
            name='tracking_number',
        ),
        migrations.AlterField(
            model_name='transit',
            name='type',
            field=models.CharField(db_index=True, max_length=255, verbose_name='Вид перевозки'),
        ),
        migrations.CreateModel(
            name='TransitSegment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('api_id', models.CharField(blank=True, max_length=255, null=True)),
                ('creation_date', models.DateField(auto_now_add=True)),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('quantity', models.IntegerField(default=0, verbose_name='Количество мест')),
                ('weight_payed', models.FloatField(default=0, verbose_name='Оплачиваемый вес')),
                ('from_addr', models.CharField(max_length=255, verbose_name='Адрес забора груза')),
                ('from_date_plan', models.DateField(blank=True, null=True, verbose_name='Плановая дата забора груза')),
                ('from_date_fact', models.DateField(blank=True, null=True, verbose_name='Фактическая дата забора груза')),
                ('to_addr', models.CharField(max_length=255, verbose_name='Адрес доставки')),
                ('to_date_plan', models.DateField(blank=True, null=True, verbose_name='Плановая дата доставки')),
                ('to_date_fact', models.DateField(blank=True, null=True, verbose_name='Фактическая дата доставки')),
                ('type', models.CharField(choices=[('auto', 'Авто'), ('plane', 'Авиа'), ('rail', 'Ж/Д'), ('ship', 'Море')], db_index=True, max_length=50, verbose_name='Вид перевозки')),
                ('price', models.FloatField(default=0, verbose_name='Ставка')),
                ('price_carrier', models.FloatField(default=0, verbose_name='Закупочная цена')),
                ('currency', models.CharField(choices=[('RUB', 'Рубль'), ('USD', 'Доллар США'), ('EUR', 'Евро')], default='RUB', max_length=3, verbose_name='Валюта')),
                ('contract', models.CharField(blank=True, max_length=255, null=True, verbose_name='Договор')),
                ('tracking_number', models.CharField(blank=True, max_length=255, null=True, verbose_name='Номер транспортного документа')),
                ('status', models.CharField(choices=[('new', 'Ожидает обработки'), ('bargain', 'Согласование ставок'), ('pending', 'Обрабатывается перевозчиком'), ('in_progress', 'В пути'), ('completed', 'Выполнено'), ('rejected', 'Отменено')], db_index=True, default='new', max_length=50, verbose_name='Статус перевозки')),
                ('comment', models.CharField(blank=True, max_length=255, null=True, verbose_name='Примечания')),
                ('carrier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segments', to='app_auth.contractor', verbose_name='Перевозчик')),
                ('transit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segments', to='orders.transit', verbose_name='Перевозка')),
            ],
        ),
    ]
