# Generated by Django 4.0.2 on 2022-05-26 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_alter_cargo_currency_alter_order_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transit',
            name='price',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Ставка'),
        ),
        migrations.AlterField(
            model_name='transit',
            name='price_carrier',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Закупочная цена'),
        ),
    ]
