# Generated by Django 4.0.2 on 2022-05-26 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0016_alter_transit_status_alter_transit_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transit',
            name='currency',
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('new', 'Новое'), ('pre_process', 'Принято в работу'), ('rejected', 'Аннулировано'), ('in_progress', 'На исполнении'), ('delivered', 'Выполнено'), ('bargain', 'Согласование ставок'), ('completed', 'Завершено')], db_index=True, default='new', max_length=50, verbose_name='Статус поручения'),
        ),
        migrations.AlterField(
            model_name='transit',
            name='quantity',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Количество мест'),
        ),
        migrations.AlterField(
            model_name='transit',
            name='value',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Заявленная стоимость'),
        ),
        migrations.AlterField(
            model_name='transit',
            name='volume',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Объем'),
        ),
        migrations.AlterField(
            model_name='transit',
            name='weight',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Вес брутто'),
        ),
        migrations.AlterField(
            model_name='transit',
            name='weight_payed',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Оплачиваемый вес'),
        ),
    ]
