# Generated by Django 4.0.2 on 2022-05-26 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0017_remove_transit_currency_alter_order_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cargo',
            name='volume_weight',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Объемный вес'),
        ),
        migrations.AlterField(
            model_name='order',
            name='quantity',
            field=models.IntegerField(blank=True, null=True, verbose_name='Количество мест'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(blank=True, choices=[('new', 'Новое'), ('pre_process', 'Принято в работу'), ('rejected', 'Аннулировано'), ('in_progress', 'На исполнении'), ('delivered', 'Выполнено'), ('bargain', 'Согласование ставок'), ('completed', 'Завершено')], db_index=True, default='new', max_length=50, null=True, verbose_name='Статус поручения'),
        ),
        migrations.AlterField(
            model_name='order',
            name='weight',
            field=models.FloatField(blank=True, null=True, verbose_name='Вес брутто'),
        ),
        migrations.AlterField(
            model_name='transit',
            name='status',
            field=models.CharField(blank=True, choices=[('carrier_select', 'Выбор перевозчика'), ('pickup', 'Забор груза'), ('in_progress', 'В пути'), ('temporary_storage', 'Груз на СВХ (ТО)'), ('transit_storage', 'Груз на транзитном складе'), ('completed', 'Доставлено'), ('rejected', 'Аннулировано')], db_index=True, default='carrier_select', max_length=50, null=True, verbose_name='Статус перевозки'),
        ),
    ]
