# Generated by Django 4.0.2 on 2022-05-26 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0018_alter_cargo_volume_weight_alter_order_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transit',
            name='insurance',
            field=models.BooleanField(default=False, verbose_name='Страхование'),
        ),
    ]
