# Generated by Django 4.0.2 on 2022-05-27 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0020_document'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='document',
            options={'verbose_name': 'документ', 'verbose_name_plural': 'документы'},
        ),
    ]
