# Generated by Django 4.0.2 on 2022-06-01 11:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0024_delete_transitstatus'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['created_at'], 'permissions': [('view_all_orders', 'Can view all orders')], 'verbose_name': 'поручение', 'verbose_name_plural': 'поручения'},
        ),
        migrations.AlterModelOptions(
            name='transit',
            options={'ordering': ['sub_number'], 'permissions': [('view_all_transits', 'Can view all transits')], 'verbose_name': 'перевозка', 'verbose_name_plural': 'перевозки'},
        ),
        migrations.RemoveField(
            model_name='order',
            name='creation_date',
        ),
        migrations.AddField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='transit',
            name='status',
            field=models.CharField(blank=True, choices=[('new', 'Новая'), ('carrier_select', 'Первичная обработка'), ('pickup', 'Забор груза'), ('in_progress', 'В пути'), ('temporary_storage', 'Груз на СВХ (ТО)'), ('transit_storage', 'Груз на транзитном складе'), ('completed', 'Доставлено'), ('rejected', 'Аннулировано')], db_index=True, default='new', max_length=50, null=True, verbose_name='Статус перевозки'),
        ),
        migrations.AlterField(
            model_name='transithistory',
            name='status',
            field=models.CharField(choices=[('new', 'Новая'), ('carrier_select', 'Первичная обработка'), ('pickup', 'Забор груза'), ('in_progress', 'В пути'), ('temporary_storage', 'Груз на СВХ (ТО)'), ('transit_storage', 'Груз на транзитном складе'), ('completed', 'Доставлено'), ('rejected', 'Аннулировано')], default='new', max_length=50, verbose_name='Статус'),
        ),
    ]
