# Generated by Django 4.0.2 on 2022-06-01 12:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0027_remove_transit_creation_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cargo',
            options={'ordering': ['created_at'], 'verbose_name': 'груз', 'verbose_name_plural': 'грузы'},
        ),
        migrations.AlterModelOptions(
            name='transitsegment',
            options={'ordering': ['created_at'], 'verbose_name': 'плечо перевозки', 'verbose_name_plural': 'плечи перевозки'},
        ),
        migrations.AddField(
            model_name='cargo',
            name='created_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='transit',
            name='created_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='transitsegment',
            name='created_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
