# Generated by Django 4.0.2 on 2022-06-01 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0028_alter_cargo_options_alter_transitsegment_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-created_at'], 'permissions': [('view_all_orders', 'Can view all orders')], 'verbose_name': 'поручение', 'verbose_name_plural': 'поручения'},
        ),
    ]
