# Generated by Django 4.0.2 on 2022-06-02 19:43

from django.db import migrations, models
import orders.models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0033_alter_transit_from_inn'),
    ]

    operations = [
        migrations.AddField(
            model_name='transitsegment',
            name='taxes',
            field=models.IntegerField(blank=True, choices=[(None, 'Без НДС'), (0, '0%'), (20, '20%')], default=20, null=True, verbose_name='НДС'),
        ),
        migrations.AlterField(
            model_name='transit',
            name='to_inn',
            field=models.BigIntegerField(validators=[orders.models.inn_validator], verbose_name='ИНН получателя'),
        ),
    ]
