# Generated by Django 4.0.2 on 2022-06-03 09:53

from django.db import migrations, models
import orders.models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0036_alter_transit_to_inn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transit',
            name='from_inn',
            field=models.BigIntegerField(blank=True, null=True, validators=[orders.models.inn_validator], verbose_name='ИНН отправителя'),
        ),
    ]
