# Generated by Django 4.0.2 on 2022-06-03 11:23

from django.db import migrations, models
import orders.models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0037_alter_transit_from_inn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transit',
            name='from_inn',
            field=models.CharField(blank=True, max_length=15, null=True, validators=[orders.models.inn_validator], verbose_name='ИНН отправителя'),
        ),
        migrations.AlterField(
            model_name='transit',
            name='to_inn',
            field=models.CharField(blank=True, max_length=15, null=True, validators=[orders.models.inn_validator], verbose_name='ИНН получателя'),
        ),
    ]
