# Generated by Django 4.0.2 on 2022-06-14 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0048_alter_cargo_quantity_alter_cargo_volume_weight_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cargo',
            name='volume_weight',
        ),
        migrations.RemoveField(
            model_name='transit',
            name='weight_payed',
        ),
    ]
