# Generated by Django 4.0.2 on 2022-07-11 10:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_auth', '0008_alter_client_inn_alter_client_kpp_remove_contact_cp_and_more'),
        ('orders', '0059_alter_cargo_package_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='transit',
            name='from_contacts',
            field=models.ManyToManyField(related_name='cnt_sent_transits', to='app_auth.Contact', verbose_name='Контактные лица'),
        ),
        migrations.AddField(
            model_name='transit',
            name='receiver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='received_transits', to='app_auth.counterparty', verbose_name='Отправитель'),
        ),
        migrations.AddField(
            model_name='transit',
            name='sender',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sent_transits', to='app_auth.counterparty', verbose_name='Отправитель'),
        ),
        migrations.AddField(
            model_name='transit',
            name='to_contacts',
            field=models.ManyToManyField(related_name='cnt_received_transits', to='app_auth.Contact', verbose_name='Контактные лица'),
        ),
        migrations.AlterField(
            model_name='transit',
            name='from_contact_email',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='transit',
            name='from_contact_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Контактное лицо'),
        ),
        migrations.AlterField(
            model_name='transit',
            name='from_contact_phone',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='transit',
            name='from_legal_addr',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Юр. адрес'),
        ),
        migrations.AlterField(
            model_name='transit',
            name='from_org',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Отправитель'),
        ),
        migrations.AlterField(
            model_name='transit',
            name='to_contact_email',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='transit',
            name='to_contact_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Контактное лицо'),
        ),
        migrations.AlterField(
            model_name='transit',
            name='to_contact_phone',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='transit',
            name='to_legal_addr',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Юр. адрес'),
        ),
        migrations.AlterField(
            model_name='transit',
            name='to_org',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Получатель'),
        ),
    ]
