# Generated by Django 4.0.2 on 2022-07-25 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_auth', '0013_alter_auditor_options_and_more'),
        ('orders', '0065_rename_auditor_order_auditors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='auditors',
            field=models.ManyToManyField(blank=True, related_name='orders', to='app_auth.Auditor', verbose_name='Аудиторы'),
        ),
    ]
