# Generated by Django 4.0.2 on 2022-09-19 18:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_auth', '0020_alter_counterparty_client_and_more'),
        ('orders', '0068_alter_aerotransit_awb_weight'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aerotransit',
            options={'verbose_name': 'Данные авиаперевозки', 'verbose_name_plural': 'Данные авиаперевозок'},
        ),
        migrations.AlterModelOptions(
            name='autotransit',
            options={'verbose_name': 'Данные автоперевозки', 'verbose_name_plural': 'Данные автоперевозок'},
        ),
        migrations.AlterField(
            model_name='extorder',
            name='from_addr',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Адрес забора груза'),
        ),
        migrations.AlterField(
            model_name='extorder',
            name='receiver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='received_ext_orders', to='app_auth.counterparty', verbose_name='Получатель'),
        ),
        migrations.AlterField(
            model_name='extorder',
            name='sender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sent_ext_orders', to='app_auth.counterparty', verbose_name='Отправитель'),
        ),
        migrations.AlterField(
            model_name='extorder',
            name='to_addr',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Адрес доставки'),
        ),
    ]
