# Generated by Django 4.0.2 on 2022-09-20 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0070_alter_transitsegment_carrier_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='autotransit',
            name='segment',
        ),
        migrations.DeleteModel(
            name='AeroTransit',
        ),
        migrations.DeleteModel(
            name='AutoTransit',
        ),
    ]
