# Generated by Django 4.0.2 on 2022-09-30 15:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_auth', '0021_counterparty_admin'),
        ('orders', '0073_extorder_from_contacts_extorder_to_contacts'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='extorder',
            options={'ordering': ['created_at'], 'permissions': [('view_all_ext_orders', 'Can view all external orders')], 'verbose_name': 'Исходящее поручение', 'verbose_name_plural': 'Исходящие поручения'},
        ),
        migrations.AlterModelOptions(
            name='transitsegment',
            options={'ordering': ['ordering_num'], 'verbose_name': 'плечо перевозки', 'verbose_name_plural': 'плечи перевозки'},
        ),
        migrations.AlterField(
            model_name='cargo',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Наименование груза'),
        ),
        migrations.AlterField(
            model_name='extorder',
            name='from_addr',
            field=models.CharField(default='', max_length=255, verbose_name='Адрес забора груза'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='extorder',
            name='receiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='received_ext_orders', to='app_auth.counterparty', verbose_name='Получатель'),
        ),
        migrations.AlterField(
            model_name='extorder',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sent_ext_orders', to='app_auth.counterparty', verbose_name='Отправитель'),
        ),
        migrations.AlterField(
            model_name='extorder',
            name='to_addr',
            field=models.CharField(default='', max_length=255, verbose_name='Адрес доставки'),
            preserve_default=False,
        ),
    ]
