# Generated by Django 4.0.8 on 2022-11-01 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0078_alter_extorder_date_alter_extorder_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='transit',
            name='number',
            field=models.CharField(blank=True, db_index=True, default='', max_length=255, verbose_name='Полный номер'),
        ),
    ]
