# Generated by Django 4.0.8 on 2022-11-01 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0079_transit_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transit',
            name='sub_number',
        ),
    ]
