# Generated by Django 4.0.8 on 2022-11-15 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0081_transitsegment_weight_brut_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='client_number',
            field=models.CharField(blank=True, max_length=50, verbose_name='Номер поручения'),
        ),
    ]
