# Generated by Django 4.0.8 on 2022-11-23 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0085_extorder_other'),
    ]

    operations = [
        migrations.AddField(
            model_name='transit',
            name='give_to',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Передать груз третьему лицу'),
        ),
        migrations.AddField(
            model_name='transit',
            name='take_from',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Забрать груз у третьего лица'),
        ),
    ]
