# Generated by Django 4.0.8 on 2022-11-23 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0086_transit_give_to_transit_take_from'),
    ]

    operations = [
        migrations.AddField(
            model_name='extorder',
            name='give_to',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Передать груз третьему лицу'),
        ),
        migrations.AddField(
            model_name='extorder',
            name='take_from',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Забрать груз у третьего лица'),
        ),
    ]
