# Generated by Django 4.0.8 on 2022-11-28 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0088_transit_from_date_wanted_transit_to_date_wanted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='type',
            field=models.CharField(choices=[('international', 'Международная перевозка'), ('internal', 'Внутрироссийская перевозка'), ('combined', 'Сборный груз'), ('courier', 'Курьерская перевозка')], db_index=True, default='internal', max_length=50, verbose_name='Вид поручения'),
        ),
        migrations.AlterField(
            model_name='transitsegment',
            name='type',
            field=models.CharField(choices=[('auto', 'Авто'), ('plane', 'Авиа'), ('rail', 'Ж/Д'), ('ship', 'Море'), ('combined', 'Сборный груз'), ('courier', 'Курьер')], db_index=True, max_length=50, verbose_name='Вид перевозки'),
        ),
    ]
