# Generated by Django 4.0.8 on 2022-12-05 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0090_order_bill_number_alter_transit_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transit',
            name='price_currency',
            field=models.CharField(choices=[('RUB', 'RUB'), ('USD', 'USD'), ('EUR', 'EUR'), ('GBP', 'GBP')], default='RUB', max_length=3, verbose_name='Валюта ставки'),
        ),
    ]
