# Generated by Django 4.1.7 on 2023-03-23 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0101_extorder_act_date_extorder_act_num_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='extorder',
            name='from_addr_short',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Пункт забора груза'),
        ),
        migrations.AddField(
            model_name='extorder',
            name='to_addr_short',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Пункт доставки'),
        ),
        migrations.AddField(
            model_name='order',
            name='active_segments',
            field=models.TextField(blank=True, editable=False, null=True, verbose_name='Активные плечи'),
        ),
        migrations.AddField(
            model_name='transit',
            name='from_addr_short',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Пункт забора груза'),
        ),
        migrations.AddField(
            model_name='transit',
            name='to_addr_short',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Пункт доставки'),
        ),
        migrations.AddField(
            model_name='transitsegment',
            name='from_addr_short',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Пункт забора груза'),
        ),
        migrations.AddField(
            model_name='transitsegment',
            name='to_addr_short',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Пункт доставки'),
        ),
    ]
