# Generated by Django 4.1.9 on 2023-07-17 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0103_order_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='extorder',
            name='necessary_docs',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Требуемые документы (для бланка ПЭ)'),
        ),
    ]
