# Generated by Django 4.1.9 on 2023-07-17 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0104_extorder_necessary_docs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transitsegment',
            name='comment',
        ),
        migrations.AddField(
            model_name='transitsegment',
            name='sub_carrier',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Субподрядчик'),
        ),
    ]
