# Generated by Django 4.1.10 on 2023-07-31 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0105_remove_transitsegment_comment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='extorder',
            name='approx_price',
            field=models.FloatField(default=0, verbose_name='Закупочная цена'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(blank=True, choices=[('new', 'Новое'), ('pre_process', 'Принято в работу'), ('rejected', 'Аннулировано'), ('in_progress', 'На исполнении'), ('delivered', 'Выполнено'), ('bargain', 'Ставка согласована'), ('docs_received', 'Документы получены'), ('completed', 'Завершено')], db_index=True, default='new', max_length=50, null=True, verbose_name='Статус поручения'),
        ),
        migrations.AlterField(
            model_name='orderhistory',
            name='status',
            field=models.CharField(choices=[('new', 'Новое'), ('pre_process', 'Принято в работу'), ('rejected', 'Аннулировано'), ('in_progress', 'На исполнении'), ('delivered', 'Выполнено'), ('bargain', 'Ставка согласована'), ('docs_received', 'Документы получены'), ('completed', 'Завершено')], default='new', max_length=50, verbose_name='Статус'),
        ),
    ]
