# Generated by Django 4.1.10 on 2023-08-09 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0107_alter_cargo_package_type_alter_extorder_approx_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='extorder',
            name='currency_check',
            field=models.CharField(choices=[('bill_date', 'на дату списания денежных средств с расчетного счета Клиента'), ('docs_date', 'на дату составления исполнительной документации')], default='bill_date', max_length=20, verbose_name='Валютная оговорка'),
        ),
    ]
