# Generated by Django 4.1.11 on 2023-09-13 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0111_alter_extorder_currency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='extorder',
            name='from_addr_eng',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Адрес забора груза (англ.)'),
        ),
        migrations.AddField(
            model_name='extorder',
            name='to_addr_eng',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Адрес доставки (англ.)'),
        ),
        migrations.AddField(
            model_name='transit',
            name='from_addr_eng',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Адрес забора груза (англ.)'),
        ),
        migrations.AddField(
            model_name='transit',
            name='to_addr_eng',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Адрес доставки (англ.)'),
        ),
        migrations.AddField(
            model_name='transitsegment',
            name='from_addr_eng',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Адрес забора груза (англ.)'),
        ),
        migrations.AddField(
            model_name='transitsegment',
            name='to_addr_eng',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Адрес доставки (англ.)'),
        ),
        migrations.AlterField(
            model_name='extorder',
            name='from_addr_short',
            field=models.CharField(default='', max_length=255, verbose_name='Пункт забора груза'),
        ),
        migrations.AlterField(
            model_name='extorder',
            name='to_addr_short',
            field=models.CharField(default='', max_length=255, verbose_name='Пункт доставки'),
        ),
        migrations.AlterField(
            model_name='order',
            name='type',
            field=models.CharField(choices=[('international', 'Международная перевозка'), ('internal', 'Внутрироссийская перевозка')], db_index=True, default='internal', max_length=50, verbose_name='Вид поручения'),
        ),
        migrations.AlterField(
            model_name='transit',
            name='from_addr_short',
            field=models.CharField(default='', max_length=255, verbose_name='Пункт забора груза'),
        ),
        migrations.AlterField(
            model_name='transit',
            name='to_addr_short',
            field=models.CharField(default='', max_length=255, verbose_name='Пункт доставки'),
        ),
        migrations.AlterField(
            model_name='transit',
            name='type',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='Тип перевозки'),
        ),
        migrations.AlterField(
            model_name='transitsegment',
            name='from_addr_short',
            field=models.CharField(default='', max_length=255, verbose_name='Пункт забора груза'),
        ),
        migrations.AlterField(
            model_name='transitsegment',
            name='to_addr_short',
            field=models.CharField(default='', max_length=255, verbose_name='Пункт доставки'),
        ),
        migrations.AlterField(
            model_name='transitsegment',
            name='type',
            field=models.CharField(choices=[('auto', 'Авто'), ('plane', 'Авиа'), ('rail', 'Ж/Д'), ('ship', 'Море'), ('combined', 'Сборный груз'), ('courier', 'Курьер')], db_index=True, max_length=50, verbose_name='Тип перевозки'),
        ),
    ]
