# Generated by Django 4.1.11 on 2023-09-17 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0112_extorder_from_addr_eng_extorder_to_addr_eng_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transit',
            name='docs_list',
            field=models.TextField(blank=True, null=True, verbose_name='Номера транспортных документов'),
        ),
    ]
