# Generated by Django 4.1.11 on 2023-09-18 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0114_extorder_gov_contr_num_order_gov_contr_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='transit',
            name='price_non_rub',
            field=models.FloatField(default=0, verbose_name='Ставка в валюте'),
        ),
        migrations.AlterField(
            model_name='transit',
            name='price',
            field=models.FloatField(default=0, verbose_name='Ставка, руб'),
        ),
        migrations.AlterField(
            model_name='transit',
            name='price_currency',
            field=models.CharField(choices=[('USD', 'USD'), ('EUR', 'EUR'), ('GBP', 'GBP'), ('INR', 'INR')], default='USD', max_length=3, verbose_name='Валюта ставки'),
        ),
    ]
