# Generated by Django 4.1.11 on 2023-09-19 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0115_transit_price_non_rub_alter_transit_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transit',
            name='price',
            field=models.FloatField(default=0, verbose_name='Ставка'),
        ),
        migrations.AlterField(
            model_name='transit',
            name='price_currency',
            field=models.CharField(choices=[('RUB', 'RUB'), ('USD', 'USD'), ('EUR', 'EUR'), ('GBP', 'GBP'), ('INR', 'INR')], default='RUB', max_length=3, verbose_name='Валюта ставки'),
        ),
        migrations.AlterField(
            model_name='transit',
            name='price_non_rub',
            field=models.FloatField(blank=True, null=True, verbose_name='Ставка в валюте'),
        ),
    ]
