# Generated by Django 4.1.11 on 2023-09-29 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0119_extorder_bill_client_extorder_currency_client_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='extorder',
            options={'ordering': ['-date', '-created_at'], 'permissions': [('view_all_ext_orders', 'Can view all external orders')], 'verbose_name': 'Исходящее поручение', 'verbose_name_plural': 'Исходящие поручения'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-order_date', '-created_at'], 'permissions': [('view_all_orders', 'Can view all orders')], 'verbose_name': 'входящее поручение', 'verbose_name_plural': 'входящие поручения'},
        ),
    ]
