# Generated by Django 4.1.11 on 2023-09-30 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0120_alter_extorder_options_alter_order_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='extorder',
            options={'ordering': ['created_at'], 'permissions': [('view_all_ext_orders', 'Can view all external orders')], 'verbose_name': 'Исходящее поручение', 'verbose_name_plural': 'Исходящие поручения'},
        ),
    ]
