# Generated by Django 4.1.11 on 2023-10-16 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0122_alter_cargo_package_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='transit',
            name='quantity_fact',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Количество мест (факт)'),
        ),
        migrations.AddField(
            model_name='transit',
            name='weight_fact',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Вес брутто (факт)'),
        ),
    ]
