# Generated by Django 4.1.11 on 2023-10-16 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0123_transit_quantity_fact_transit_weight_fact'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='quantity_fact',
            field=models.IntegerField(blank=True, null=True, verbose_name='Количество мест (факт)'),
        ),
        migrations.AddField(
            model_name='order',
            name='weight_fact',
            field=models.FloatField(blank=True, null=True, verbose_name='Вес брутто (факт)'),
        ),
    ]
