# Generated by Django 4.1.11 on 2023-11-23 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0125_alter_cargo_package_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='client_number',
            field=models.CharField(blank=True, max_length=70, verbose_name='Номер поручения'),
        ),
        migrations.AlterField(
            model_name='order',
            name='inner_number',
            field=models.CharField(blank=True, max_length=70, verbose_name='Внутренний номер'),
        ),
    ]
