# Generated by Django 4.1.13 on 2023-12-21 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0127_transit_price_approval_req_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='extorder',
            name='insurance_currency',
            field=models.CharField(choices=[('RUB', 'RUB'), ('USD', 'USD'), ('EUR', 'EUR'), ('GBP', 'GBP'), ('INR', 'INR')], default='RUB', max_length=3, verbose_name='Валюта страхования'),
        ),
        migrations.AddField(
            model_name='extorder',
            name='insurance_value',
            field=models.FloatField(default=0, verbose_name='Страховая премия'),
        ),
    ]
