# Generated by Django 4.1.13 on 2024-01-06 19:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0001_initial'),
        ('orders', '0129_transitsegment_bill_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transitsegment',
            name='bill_position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='segments', to='pricing.billposition'),
        ),
    ]
