# Generated by Django 4.1.13 on 2024-01-15 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0130_alter_transitsegment_bill_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='cargo',
            name='last_update',
            field=models.DateTimeField(auto_now=True, verbose_name='Время последнего изменения'),
        ),
    ]
