# Generated by Django 4.1.13 on 2024-01-24 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0131_cargo_last_update'),
    ]

    operations = [
        migrations.AddField(
            model_name='extorder',
            name='type',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Тип перевозки'),
        ),
    ]
