# Generated by Django 4.1.13 on 2024-03-18 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0132_extorder_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extorder',
            name='currency',
            field=models.CharField(choices=[('RUB', 'RUB'), ('USD', 'USD'), ('EUR', 'EUR'), ('GBP', 'GBP'), ('INR', 'INR'), ('CNY', 'CNY')], default='RUB', max_length=3, verbose_name='Валюта'),
        ),
        migrations.AlterField(
            model_name='extorder',
            name='currency_client',
            field=models.CharField(choices=[('RUB', 'RUB'), ('USD', 'USD'), ('EUR', 'EUR'), ('GBP', 'GBP'), ('INR', 'INR'), ('CNY', 'CNY')], default='RUB', max_length=3, verbose_name='Валюта заказчика'),
        ),
        migrations.AlterField(
            model_name='extorder',
            name='insurance_currency',
            field=models.CharField(choices=[('RUB', 'RUB'), ('USD', 'USD'), ('EUR', 'EUR'), ('GBP', 'GBP'), ('INR', 'INR'), ('CNY', 'CNY')], default='RUB', max_length=3, verbose_name='Валюта страхования'),
        ),
        migrations.AlterField(
            model_name='order',
            name='insurance_currency',
            field=models.CharField(choices=[('RUB', 'RUB'), ('USD', 'USD'), ('EUR', 'EUR'), ('GBP', 'GBP'), ('INR', 'INR'), ('CNY', 'CNY')], default='RUB', max_length=3, verbose_name='Валюта страхования'),
        ),
        migrations.AlterField(
            model_name='transit',
            name='currency',
            field=models.CharField(choices=[('RUB', 'RUB'), ('USD', 'USD'), ('EUR', 'EUR'), ('GBP', 'GBP'), ('INR', 'INR'), ('CNY', 'CNY')], default='RUB', max_length=3, verbose_name='Валюта'),
        ),
        migrations.AlterField(
            model_name='transit',
            name='price_currency',
            field=models.CharField(choices=[('RUB', 'RUB'), ('USD', 'USD'), ('EUR', 'EUR'), ('GBP', 'GBP'), ('INR', 'INR'), ('CNY', 'CNY')], default='RUB', max_length=3, verbose_name='Валюта ставки'),
        ),
        migrations.AlterField(
            model_name='transitsegment',
            name='currency',
            field=models.CharField(blank=True, choices=[('RUB', 'RUB'), ('USD', 'USD'), ('EUR', 'EUR'), ('GBP', 'GBP'), ('INR', 'INR'), ('CNY', 'CNY')], default='RUB', max_length=3, null=True, verbose_name='Валюта'),
        ),
    ]
