# Generated by Django 4.1.13 on 2024-08-01 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0133_alter_extorder_currency_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transitsegment',
            name='type',
            field=models.CharField(choices=[('auto', 'Авто'), ('plane', 'Авиа'), ('rail', 'Ж/Д'), ('ship', 'Море'), ('combined', 'Сборный груз'), ('courier', 'Курьер'), ('evaluation', 'Оценка'), ('insurance', 'Страхование'), ('customs', 'Таможенное оформление'), ('terminal', 'Терминальная обработка'), ('utilization', 'Утилизация')], db_index=True, max_length=50, verbose_name='Тип перевозки'),
        ),
    ]
