# Generated by Django 4.0.2 on 2022-05-16 15:45

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MainTextBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Заголовок')),
                ('body', ckeditor.fields.RichTextField(verbose_name='Текст')),
                ('img', models.ImageField(blank=True, null=True, upload_to='images', verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'блок главной страницы',
                'verbose_name_plural': 'Главная страница',
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Наименование')),
                ('unit', models.CharField(max_length=100, verbose_name='Единица измерения')),
                ('price', models.CharField(max_length=100, verbose_name='Цена')),
            ],
            options={
                'verbose_name': 'позицию прайс-листа',
                'verbose_name_plural': 'Прайс-лист',
            },
        ),
        migrations.CreateModel(
            name='Requisite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Наименование реквизита (например, ИНН)')),
                ('value', models.CharField(max_length=255, verbose_name='Значение реквизита')),
            ],
            options={
                'verbose_name': 'реквизит',
                'verbose_name_plural': 'Реквизиты',
            },
        ),
    ]
