# Generated by Django 4.0.2 on 2022-09-20 13:59

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('static_pages', '0002_delete_position_delete_requisite'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название вакансии')),
                ('salary', models.FloatField(blank=True, null=True, verbose_name='Заработная плата')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('body', ckeditor.fields.RichTextField(verbose_name='Описание вакансии')),
            ],
            options={
                'verbose_name': 'вакансия',
                'verbose_name_plural': 'вакансии',
            },
        ),
    ]
