# Generated by Django 4.1.13 on 2024-01-06 18:01

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0128_extorder_insurance_currency_extorder_insurance_value'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderPrice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('last_update', models.DateTimeField(auto_now=True, verbose_name='Время последнего изменения')),
                ('price_date', models.DateField(verbose_name='Дата ставки')),
                ('multi_currency_string', models.CharField(blank=True, max_length=255, null=True, verbose_name='Сумма')),
                ('rub_equivalent', models.FloatField(blank=True, null=True, verbose_name='Рублевый эквивалент')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='orders.order', verbose_name='Входящее поручение')),
            ],
        ),
        migrations.CreateModel(
            name='BillPosition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('last_update', models.DateTimeField(auto_now=True, verbose_name='Время последнего изменения')),
                ('value', models.FloatField(verbose_name='Сумма')),
                ('currency', models.CharField(choices=[('RUB', 'RUB'), ('USD', 'USD'), ('EUR', 'EUR'), ('GBP', 'GBP'), ('INR', 'INR')], max_length=3, verbose_name='Валюта')),
                ('taxes', models.IntegerField(blank=True, choices=[(None, 'Без НДС'), (0, '0%'), (20, '20%')], default=20, null=True, verbose_name='НДС')),
                ('bill_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='Номер счета')),
                ('run_start', models.TextField(blank=True, null=True, verbose_name='Начало маршрута')),
                ('run_end', models.TextField(blank=True, null=True, verbose_name='Конец маршрута')),
                ('docs_list', models.TextField(blank=True, null=True, verbose_name='Номера транспортных документов')),
                ('from_date_fact', models.DateField(blank=True, null=True, verbose_name='Фактическая дата забора груза')),
                ('to_date_fact', models.DateField(blank=True, null=True, verbose_name='Фактическая дата доставки')),
                ('quantity', models.IntegerField(blank=True, default=0, null=True, verbose_name='Количество мест')),
                ('weight_payed', models.FloatField(blank=True, default=0, null=True, verbose_name='Оплачиваемый вес')),
                ('value_wo_taxes', models.FloatField(blank=True, null=True, verbose_name='Сумма без НДС')),
                ('taxes_value', models.FloatField(blank=True, null=True, verbose_name='Сумма НДС')),
                ('order_price', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='pricing.orderprice', verbose_name='Суммирующая ставка')),
                ('transit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='orders.transit', verbose_name='Перевозка')),
            ],
        ),
    ]
