# Generated by Django 4.1.13 on 2024-01-15 20:31

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SyncLogEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='Время создания')),
                ('last_update', models.DateTimeField(auto_now=True, verbose_name='Время последнего изменения')),
                ('object_type', models.CharField(db_index=True, max_length=255, verbose_name='Тип объекта')),
                ('node', models.CharField(db_index=True, max_length=255, verbose_name='Имя ноды')),
                ('obj_pk', models.UUIDField(verbose_name='ID объекта')),
                ('obj_last_update', models.DateTimeField(verbose_name='Время последнего изменения объекта')),
            ],
            options={
                'unique_together': {('node', 'object_type', 'obj_pk')},
            },
        ),
    ]
