version: "3.9"

volumes:
  static-data:
    driver: vieux/sshfs
    driver_opts:
      sshcmd: "d_fedorov@192.168.21.23:/tmp/media"
      password: "Parol123"
      allow_other: ""

services:
  app:
    build:
      context: .
    restart: always
    volumes:
      - ./app:/app
      - static-data:/vol/web
    environment:
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - SECRET_KEY=${SECRET_KEY}
      - ALLOWED_HOSTS=${ALLOWED_HOSTS}
      - EMAIL_HOST=${EMAIL_HOST}
      - EMAIL_PORT=${EMAIL_PORT}
      - EMAIL_HOST_USER=${EMAIL_HOST_USER}
      - EMAIL_HOST_PASSWORD=${EMAIL_HOST_PASSWORD}
      - EMAIL_USE_SSL=${EMAIL_USE_SSL}
      - DEBUG=${DEBUG}

  proxy:
    build:
      context: ./proxy
    restart: always
    depends_on:
      - app
    ports:
      - "80:80"
    environment:
      - APP_HOST=app
      - APP_PORT=9000
      - LISTEN_PORT=80
    volumes:
      - static-data:/vol/static