# Generated by Django 4.0.2 on 2022-03-23 12:15

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app_auth', '0002_alter_user_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('inn', models.IntegerField(db_index=True)),
                ('kpp', models.IntegerField(db_index=True)),
                ('short_name', models.CharField(max_length=255, verbose_name='Краткое наименование')),
                ('legal_address', models.CharField(max_length=255)),
                ('fact_address', models.CharField(max_length=255)),
                ('num_prefix', models.CharField(blank=True, max_length=5, null=True)),
            ],
            options={
                'verbose_name': 'client',
                'verbose_name_plural': 'clients',
                'permissions': [('view_all_clients', 'Can view all clients')],
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('last_name', models.CharField(max_length=255, verbose_name='фамилия')),
                ('first_name', models.CharField(max_length=255, verbose_name='имя')),
                ('second_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='отчество')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='email')),
                ('phone', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Contractor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('inn', models.IntegerField(db_index=True)),
                ('kpp', models.IntegerField(db_index=True)),
                ('short_name', models.CharField(max_length=255, verbose_name='Краткое наименование')),
                ('legal_address', models.CharField(max_length=255)),
                ('fact_address', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'contractor',
                'verbose_name_plural': 'contractors',
            },
        ),
        migrations.CreateModel(
            name='Counterparty',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('inn', models.IntegerField(db_index=True)),
                ('kpp', models.IntegerField(db_index=True)),
                ('short_name', models.CharField(max_length=255, verbose_name='Краткое наименование')),
                ('legal_address', models.CharField(max_length=255)),
                ('fact_address', models.CharField(max_length=255)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='counterparties', to='app_auth.client')),
            ],
            options={
                'verbose_name': 'client counterparty',
                'verbose_name_plural': 'client counterparties',
            },
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': [('view_all_users', 'Can view all users')], 'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_org_admin',
        ),
        migrations.RemoveField(
            model_name='user',
            name='org',
        ),
        migrations.DeleteModel(
            name='Organisation',
        ),
        migrations.AddField(
            model_name='contact',
            name='cp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_auth.counterparty'),
        ),
        migrations.AddField(
            model_name='user',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='app_auth.client', verbose_name='организация'),
        ),
    ]
