# Generated by Django 4.0.2 on 2022-06-01 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_auth', '0005_alter_client_inn_alter_client_kpp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='kpp',
            field=models.BigIntegerField(blank=True, db_index=True, null=True, verbose_name='КПП'),
        ),
        migrations.AlterField(
            model_name='contractor',
            name='kpp',
            field=models.BigIntegerField(blank=True, db_index=True, null=True, verbose_name='КПП'),
        ),
        migrations.AlterField(
            model_name='counterparty',
            name='kpp',
            field=models.BigIntegerField(blank=True, db_index=True, null=True, verbose_name='КПП'),
        ),
    ]
