# Generated by Django 4.0.2 on 2022-07-11 10:49

import app_auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_auth', '0007_alter_client_inn_alter_contractor_inn_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='inn',
            field=models.CharField(blank=True, db_index=True, max_length=12, null=True, validators=[app_auth.models.inn_validator], verbose_name='ИНН'),
        ),
        migrations.AlterField(
            model_name='client',
            name='kpp',
            field=models.CharField(blank=True, db_index=True, max_length=12, null=True, verbose_name='КПП'),
        ),
        migrations.RemoveField(
            model_name='contact',
            name='cp',
        ),
        migrations.AddField(
            model_name='contact',
            name='cp',
            field=models.ManyToManyField(to='app_auth.Counterparty', verbose_name='Контрагенты'),
        ),
        migrations.AlterField(
            model_name='contractor',
            name='inn',
            field=models.CharField(blank=True, db_index=True, max_length=12, null=True, validators=[app_auth.models.inn_validator], verbose_name='ИНН'),
        ),
        migrations.AlterField(
            model_name='contractor',
            name='kpp',
            field=models.CharField(blank=True, db_index=True, max_length=12, null=True, verbose_name='КПП'),
        ),
        migrations.AlterField(
            model_name='counterparty',
            name='inn',
            field=models.CharField(blank=True, db_index=True, max_length=12, null=True, validators=[app_auth.models.inn_validator], verbose_name='ИНН'),
        ),
        migrations.AlterField(
            model_name='counterparty',
            name='kpp',
            field=models.CharField(blank=True, db_index=True, max_length=12, null=True, verbose_name='КПП'),
        ),
    ]
