# Generated by Django 4.0.2 on 2022-07-20 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_auth', '0010_reportparams'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportparams',
            name='report_class',
            field=models.CharField(default='order', max_length=255, verbose_name='Тип отчета'),
        ),
    ]
