# Generated by Django 4.0.2 on 2022-07-22 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_auth', '0012_auditor_user_auditor'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auditor',
            options={'verbose_name': 'аудитор', 'verbose_name_plural': 'аудиторы'},
        ),
        migrations.AlterField(
            model_name='auditor',
            name='controlled_clients',
            field=models.ManyToManyField(related_name='auditors', to='app_auth.Client', verbose_name='Поднадзорные организации'),
        ),
    ]
