# Generated by Django 4.0.2 on 2022-08-08 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_auth', '0017_user_carrier_user_user_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='carrier',
            new_name='contractor',
        ),
    ]
