# Generated by Django 4.0.2 on 2022-08-23 17:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_auth', '0018_rename_carrier_user_contractor'),
    ]

    operations = [
        migrations.AddField(
            model_name='counterparty',
            name='contractor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='counterparties', to='app_auth.contractor'),
        ),
        migrations.AlterField(
            model_name='counterparty',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='counterparties', to='app_auth.client'),
        ),
        migrations.AlterField(
            model_name='user',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='app_auth.client', verbose_name='заказчик'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('manager', 'Менеджер'), ('client_simple', 'Заказчик (обычный)'), ('client_advanced', 'Заказчик (расширенный)'), ('auditor_simple', 'Аудитор (обычный)'), ('auditor_advanced', 'Аудитор (расширенный)'), ('contractor_simple', 'Подрядчик (обычный)'), ('contractor_advanced', 'Подрядчик (расширенный)')], default='manager', max_length=25, verbose_name='тип пользователя'),
        ),
    ]
