# Generated by Django 4.0.8 on 2022-11-17 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_auth', '0024_contractorcontract_clientcontract'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='contract',
        ),
        migrations.RemoveField(
            model_name='client',
            name='contract_expiration_date',
        ),
        migrations.RemoveField(
            model_name='client',
            name='contract_sign_date',
        ),
        migrations.RemoveField(
            model_name='contractor',
            name='contract',
        ),
        migrations.RemoveField(
            model_name='contractor',
            name='contract_expiration_date',
        ),
        migrations.RemoveField(
            model_name='contractor',
            name='contract_sign_date',
        ),
    ]
