# Generated by Django 4.0.8 on 2022-12-27 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_auth', '0025_remove_client_contract_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reportparams',
            name='merge_segments',
        ),
        migrations.AddField(
            model_name='reportparams',
            name='_ext_order_fields',
            field=models.TextField(default='', verbose_name='Поля исходящего поручения'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reportparams',
            name='_order_fields',
            field=models.TextField(verbose_name='Поля входящего поручения'),
        ),
    ]
