# Generated by Django 4.0.8 on 2022-11-17 17:03

from django.db import migrations, models
import uuid


def fill_uuids(apps, schema_editor):
    ClientContract = apps.get_model('app_auth', 'ClientContract')
    ContractorContract = apps.get_model('app_auth', 'ContractorContract')
    for i in ClientContract.objects.all():
        i.u_id = uuid.uuid4()
        i.save()
    for i in ContractorContract.objects.all():
        i.u_id = uuid.uuid4()
        i.save()


class Migration(migrations.Migration):

    dependencies = [
        ('app_auth', '0025_remove_client_contract_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientcontract',
            name='u_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name='contractorcontract',
            name='u_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.RunPython(fill_uuids, reverse_code=migrations.RunPython.noop),
        migrations.AlterField(
            model_name='clientcontract',
            name='u_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='contractorcontract',
            name='u_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
