# Generated by Django 4.0.8 on 2022-11-17 17:50

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app_auth', '0026_clientcontract_u_id_contractorcontract_u_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientcontract',
            name='u_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='clientcontract',
            name='id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='contractorcontract',
            name='u_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='contractorcontract',
            name='id',
            field=models.IntegerField(null=True),
        ),
    ]
